// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ActionOutcomeData {
  bytes32 actionId;
  uint256 weaponId;
  bytes32 attackerId;
  bytes32 defenderId;
  bool hit;
  bool miss;
  bool crit;
  int256 attackerDamageDelt;
  int256 defenderDamageDelt;
  bool attackerDied;
  bool defenderDied;
  uint256 blockNumber;
  uint256 timestamp;
}

library ActionOutcome {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "ActionOutcome", typeId: RESOURCE_OFFCHAIN_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x6f745544000000000000000000000000416374696f6e4f7574636f6d65000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x01050d0020202020010101202001012020000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, uint256, uint256)
  Schema constant _keySchema = Schema.wrap(0x006003005f1f1f00000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32, uint256, bytes32, bytes32, bool, bool, bool, int256, int256, bool, bool, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x01050d005f1f5f5f6060603f3f60601f1f000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "encounterId";
    keyNames[1] = "currentTurn";
    keyNames[2] = "actionNumber";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](13);
    fieldNames[0] = "actionId";
    fieldNames[1] = "weaponId";
    fieldNames[2] = "attackerId";
    fieldNames[3] = "defenderId";
    fieldNames[4] = "hit";
    fieldNames[5] = "miss";
    fieldNames[6] = "crit";
    fieldNames[7] = "attackerDamageDelt";
    fieldNames[8] = "defenderDamageDelt";
    fieldNames[9] = "attackerDied";
    fieldNames[10] = "defenderDied";
    fieldNames[11] = "blockNumber";
    fieldNames[12] = "timestamp";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Set actionId.
   */
  function setActionId(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bytes32 actionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((actionId)), _fieldLayout);
  }

  /**
   * @notice Set actionId.
   */
  function _setActionId(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bytes32 actionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((actionId)), _fieldLayout);
  }

  /**
   * @notice Set weaponId.
   */
  function setWeaponId(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, uint256 weaponId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((weaponId)), _fieldLayout);
  }

  /**
   * @notice Set weaponId.
   */
  function _setWeaponId(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, uint256 weaponId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((weaponId)), _fieldLayout);
  }

  /**
   * @notice Set attackerId.
   */
  function setAttackerId(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bytes32 attackerId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((attackerId)), _fieldLayout);
  }

  /**
   * @notice Set attackerId.
   */
  function _setAttackerId(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bytes32 attackerId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((attackerId)), _fieldLayout);
  }

  /**
   * @notice Set defenderId.
   */
  function setDefenderId(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bytes32 defenderId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((defenderId)), _fieldLayout);
  }

  /**
   * @notice Set defenderId.
   */
  function _setDefenderId(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bytes32 defenderId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((defenderId)), _fieldLayout);
  }

  /**
   * @notice Set hit.
   */
  function setHit(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bool hit) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((hit)), _fieldLayout);
  }

  /**
   * @notice Set hit.
   */
  function _setHit(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bool hit) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((hit)), _fieldLayout);
  }

  /**
   * @notice Set miss.
   */
  function setMiss(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bool miss) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((miss)), _fieldLayout);
  }

  /**
   * @notice Set miss.
   */
  function _setMiss(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bool miss) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((miss)), _fieldLayout);
  }

  /**
   * @notice Set crit.
   */
  function setCrit(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bool crit) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((crit)), _fieldLayout);
  }

  /**
   * @notice Set crit.
   */
  function _setCrit(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bool crit) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((crit)), _fieldLayout);
  }

  /**
   * @notice Set attackerDamageDelt.
   */
  function setAttackerDamageDelt(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    int256 attackerDamageDelt
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((attackerDamageDelt)), _fieldLayout);
  }

  /**
   * @notice Set attackerDamageDelt.
   */
  function _setAttackerDamageDelt(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    int256 attackerDamageDelt
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((attackerDamageDelt)), _fieldLayout);
  }

  /**
   * @notice Set defenderDamageDelt.
   */
  function setDefenderDamageDelt(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    int256 defenderDamageDelt
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((defenderDamageDelt)), _fieldLayout);
  }

  /**
   * @notice Set defenderDamageDelt.
   */
  function _setDefenderDamageDelt(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    int256 defenderDamageDelt
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((defenderDamageDelt)), _fieldLayout);
  }

  /**
   * @notice Set attackerDied.
   */
  function setAttackerDied(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bool attackerDied) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((attackerDied)), _fieldLayout);
  }

  /**
   * @notice Set attackerDied.
   */
  function _setAttackerDied(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    bool attackerDied
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 9, abi.encodePacked((attackerDied)), _fieldLayout);
  }

  /**
   * @notice Set defenderDied.
   */
  function setDefenderDied(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, bool defenderDied) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 10, abi.encodePacked((defenderDied)), _fieldLayout);
  }

  /**
   * @notice Set defenderDied.
   */
  function _setDefenderDied(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    bool defenderDied
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 10, abi.encodePacked((defenderDied)), _fieldLayout);
  }

  /**
   * @notice Set blockNumber.
   */
  function setBlockNumber(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    uint256 blockNumber
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 11, abi.encodePacked((blockNumber)), _fieldLayout);
  }

  /**
   * @notice Set blockNumber.
   */
  function _setBlockNumber(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    uint256 blockNumber
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 11, abi.encodePacked((blockNumber)), _fieldLayout);
  }

  /**
   * @notice Set timestamp.
   */
  function setTimestamp(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, uint256 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 12, abi.encodePacked((timestamp)), _fieldLayout);
  }

  /**
   * @notice Set timestamp.
   */
  function _setTimestamp(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber, uint256 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setStaticField(_tableId, _keyTuple, 12, abi.encodePacked((timestamp)), _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    bytes32 actionId,
    uint256 weaponId,
    bytes32 attackerId,
    bytes32 defenderId,
    bool hit,
    bool miss,
    bool crit,
    int256 attackerDamageDelt,
    int256 defenderDamageDelt,
    bool attackerDied,
    bool defenderDied,
    uint256 blockNumber,
    uint256 timestamp
  ) internal {
    bytes memory _staticData = encodeStatic(
      actionId,
      weaponId,
      attackerId,
      defenderId,
      hit,
      miss,
      crit,
      attackerDamageDelt,
      defenderDamageDelt,
      attackerDied,
      defenderDied,
      blockNumber,
      timestamp
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    bytes32 actionId,
    uint256 weaponId,
    bytes32 attackerId,
    bytes32 defenderId,
    bool hit,
    bool miss,
    bool crit,
    int256 attackerDamageDelt,
    int256 defenderDamageDelt,
    bool attackerDied,
    bool defenderDied,
    uint256 blockNumber,
    uint256 timestamp
  ) internal {
    bytes memory _staticData = encodeStatic(
      actionId,
      weaponId,
      attackerId,
      defenderId,
      hit,
      miss,
      crit,
      attackerDamageDelt,
      defenderDamageDelt,
      attackerDied,
      defenderDied,
      blockNumber,
      timestamp
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    ActionOutcomeData memory _table
  ) internal {
    bytes memory _staticData = encodeStatic(
      _table.actionId,
      _table.weaponId,
      _table.attackerId,
      _table.defenderId,
      _table.hit,
      _table.miss,
      _table.crit,
      _table.attackerDamageDelt,
      _table.defenderDamageDelt,
      _table.attackerDied,
      _table.defenderDied,
      _table.blockNumber,
      _table.timestamp
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber,
    ActionOutcomeData memory _table
  ) internal {
    bytes memory _staticData = encodeStatic(
      _table.actionId,
      _table.weaponId,
      _table.attackerId,
      _table.defenderId,
      _table.hit,
      _table.miss,
      _table.crit,
      _table.attackerDamageDelt,
      _table.defenderDamageDelt,
      _table.attackerDied,
      _table.defenderDied,
      _table.blockNumber,
      _table.timestamp
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      bytes32 actionId,
      uint256 weaponId,
      bytes32 attackerId,
      bytes32 defenderId,
      bool hit,
      bool miss,
      bool crit,
      int256 attackerDamageDelt,
      int256 defenderDamageDelt,
      bool attackerDied,
      bool defenderDied,
      uint256 blockNumber,
      uint256 timestamp
    )
  {
    actionId = (Bytes.getBytes32(_blob, 0));

    weaponId = (uint256(Bytes.getBytes32(_blob, 32)));

    attackerId = (Bytes.getBytes32(_blob, 64));

    defenderId = (Bytes.getBytes32(_blob, 96));

    hit = (_toBool(uint8(Bytes.getBytes1(_blob, 128))));

    miss = (_toBool(uint8(Bytes.getBytes1(_blob, 129))));

    crit = (_toBool(uint8(Bytes.getBytes1(_blob, 130))));

    attackerDamageDelt = (int256(uint256(Bytes.getBytes32(_blob, 131))));

    defenderDamageDelt = (int256(uint256(Bytes.getBytes32(_blob, 163))));

    attackerDied = (_toBool(uint8(Bytes.getBytes1(_blob, 195))));

    defenderDied = (_toBool(uint8(Bytes.getBytes1(_blob, 196))));

    blockNumber = (uint256(Bytes.getBytes32(_blob, 197)));

    timestamp = (uint256(Bytes.getBytes32(_blob, 229)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (ActionOutcomeData memory _table) {
    (
      _table.actionId,
      _table.weaponId,
      _table.attackerId,
      _table.defenderId,
      _table.hit,
      _table.miss,
      _table.crit,
      _table.attackerDamageDelt,
      _table.defenderDamageDelt,
      _table.attackerDied,
      _table.defenderDied,
      _table.blockNumber,
      _table.timestamp
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 encounterId, uint256 currentTurn, uint256 actionNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    bytes32 actionId,
    uint256 weaponId,
    bytes32 attackerId,
    bytes32 defenderId,
    bool hit,
    bool miss,
    bool crit,
    int256 attackerDamageDelt,
    int256 defenderDamageDelt,
    bool attackerDied,
    bool defenderDied,
    uint256 blockNumber,
    uint256 timestamp
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        actionId,
        weaponId,
        attackerId,
        defenderId,
        hit,
        miss,
        crit,
        attackerDamageDelt,
        defenderDamageDelt,
        attackerDied,
        defenderDied,
        blockNumber,
        timestamp
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bytes32 actionId,
    uint256 weaponId,
    bytes32 attackerId,
    bytes32 defenderId,
    bool hit,
    bool miss,
    bool crit,
    int256 attackerDamageDelt,
    int256 defenderDamageDelt,
    bool attackerDied,
    bool defenderDied,
    uint256 blockNumber,
    uint256 timestamp
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      actionId,
      weaponId,
      attackerId,
      defenderId,
      hit,
      miss,
      crit,
      attackerDamageDelt,
      defenderDamageDelt,
      attackerDied,
      defenderDied,
      blockNumber,
      timestamp
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(
    bytes32 encounterId,
    uint256 currentTurn,
    uint256 actionNumber
  ) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = encounterId;
    _keyTuple[1] = bytes32(uint256(currentTurn));
    _keyTuple[2] = bytes32(uint256(actionNumber));

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
