// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct CharacterEquipmentData {
  int256 strBonus;
  int256 agiBonus;
  int256 intBonus;
  int256 hpBonus;
  int256 armor;
  uint256[] equippedArmor;
  uint256[] equippedWeapons;
  uint256[] equippedSpells;
  uint256[] equippedConsumables;
  uint256[] equippedAccessories;
}

library CharacterEquipment {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "CharacterEquipme", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462554400000000000000000000000043686172616374657245717569706d65);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00a0050520202020200000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (int256, int256, int256, int256, int256, uint256[], uint256[], uint256[], uint256[], uint256[])
  Schema constant _valueSchema = Schema.wrap(0x00a005053f3f3f3f3f8181818181000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "characterId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](10);
    fieldNames[0] = "strBonus";
    fieldNames[1] = "agiBonus";
    fieldNames[2] = "intBonus";
    fieldNames[3] = "hpBonus";
    fieldNames[4] = "armor";
    fieldNames[5] = "equippedArmor";
    fieldNames[6] = "equippedWeapons";
    fieldNames[7] = "equippedSpells";
    fieldNames[8] = "equippedConsumables";
    fieldNames[9] = "equippedAccessories";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get strBonus.
   */
  function getStrBonus(bytes32 characterId) internal view returns (int256 strBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get strBonus.
   */
  function _getStrBonus(bytes32 characterId) internal view returns (int256 strBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set strBonus.
   */
  function setStrBonus(bytes32 characterId, int256 strBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((strBonus)), _fieldLayout);
  }

  /**
   * @notice Set strBonus.
   */
  function _setStrBonus(bytes32 characterId, int256 strBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((strBonus)), _fieldLayout);
  }

  /**
   * @notice Get agiBonus.
   */
  function getAgiBonus(bytes32 characterId) internal view returns (int256 agiBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get agiBonus.
   */
  function _getAgiBonus(bytes32 characterId) internal view returns (int256 agiBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set agiBonus.
   */
  function setAgiBonus(bytes32 characterId, int256 agiBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((agiBonus)), _fieldLayout);
  }

  /**
   * @notice Set agiBonus.
   */
  function _setAgiBonus(bytes32 characterId, int256 agiBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((agiBonus)), _fieldLayout);
  }

  /**
   * @notice Get intBonus.
   */
  function getIntBonus(bytes32 characterId) internal view returns (int256 intBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get intBonus.
   */
  function _getIntBonus(bytes32 characterId) internal view returns (int256 intBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set intBonus.
   */
  function setIntBonus(bytes32 characterId, int256 intBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((intBonus)), _fieldLayout);
  }

  /**
   * @notice Set intBonus.
   */
  function _setIntBonus(bytes32 characterId, int256 intBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((intBonus)), _fieldLayout);
  }

  /**
   * @notice Get hpBonus.
   */
  function getHpBonus(bytes32 characterId) internal view returns (int256 hpBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get hpBonus.
   */
  function _getHpBonus(bytes32 characterId) internal view returns (int256 hpBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set hpBonus.
   */
  function setHpBonus(bytes32 characterId, int256 hpBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((hpBonus)), _fieldLayout);
  }

  /**
   * @notice Set hpBonus.
   */
  function _setHpBonus(bytes32 characterId, int256 hpBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((hpBonus)), _fieldLayout);
  }

  /**
   * @notice Get armor.
   */
  function getArmor(bytes32 characterId) internal view returns (int256 armor) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get armor.
   */
  function _getArmor(bytes32 characterId) internal view returns (int256 armor) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set armor.
   */
  function setArmor(bytes32 characterId, int256 armor) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((armor)), _fieldLayout);
  }

  /**
   * @notice Set armor.
   */
  function _setArmor(bytes32 characterId, int256 armor) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((armor)), _fieldLayout);
  }

  /**
   * @notice Get equippedArmor.
   */
  function getEquippedArmor(bytes32 characterId) internal view returns (uint256[] memory equippedArmor) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Get equippedArmor.
   */
  function _getEquippedArmor(bytes32 characterId) internal view returns (uint256[] memory equippedArmor) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Set equippedArmor.
   */
  function setEquippedArmor(bytes32 characterId, uint256[] memory equippedArmor) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((equippedArmor)));
  }

  /**
   * @notice Set equippedArmor.
   */
  function _setEquippedArmor(bytes32 characterId, uint256[] memory equippedArmor) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((equippedArmor)));
  }

  /**
   * @notice Get the length of equippedArmor.
   */
  function lengthEquippedArmor(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of equippedArmor.
   */
  function _lengthEquippedArmor(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of equippedArmor.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemEquippedArmor(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Get an item of equippedArmor.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemEquippedArmor(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Push an element to equippedArmor.
   */
  function pushEquippedArmor(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to equippedArmor.
   */
  function _pushEquippedArmor(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from equippedArmor.
   */
  function popEquippedArmor(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from equippedArmor.
   */
  function _popEquippedArmor(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Update an element of equippedArmor at `_index`.
   */
  function updateEquippedArmor(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of equippedArmor at `_index`.
   */
  function _updateEquippedArmor(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get equippedWeapons.
   */
  function getEquippedWeapons(bytes32 characterId) internal view returns (uint256[] memory equippedWeapons) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 1);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Get equippedWeapons.
   */
  function _getEquippedWeapons(bytes32 characterId) internal view returns (uint256[] memory equippedWeapons) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 1);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Set equippedWeapons.
   */
  function setEquippedWeapons(bytes32 characterId, uint256[] memory equippedWeapons) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 1, EncodeArray.encode((equippedWeapons)));
  }

  /**
   * @notice Set equippedWeapons.
   */
  function _setEquippedWeapons(bytes32 characterId, uint256[] memory equippedWeapons) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 1, EncodeArray.encode((equippedWeapons)));
  }

  /**
   * @notice Get the length of equippedWeapons.
   */
  function lengthEquippedWeapons(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 1);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of equippedWeapons.
   */
  function _lengthEquippedWeapons(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 1);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of equippedWeapons.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemEquippedWeapons(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 1, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Get an item of equippedWeapons.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemEquippedWeapons(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 1, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Push an element to equippedWeapons.
   */
  function pushEquippedWeapons(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 1, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to equippedWeapons.
   */
  function _pushEquippedWeapons(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 1, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from equippedWeapons.
   */
  function popEquippedWeapons(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 1, 32);
  }

  /**
   * @notice Pop an element from equippedWeapons.
   */
  function _popEquippedWeapons(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 1, 32);
  }

  /**
   * @notice Update an element of equippedWeapons at `_index`.
   */
  function updateEquippedWeapons(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 1, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of equippedWeapons at `_index`.
   */
  function _updateEquippedWeapons(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 1, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get equippedSpells.
   */
  function getEquippedSpells(bytes32 characterId) internal view returns (uint256[] memory equippedSpells) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 2);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Get equippedSpells.
   */
  function _getEquippedSpells(bytes32 characterId) internal view returns (uint256[] memory equippedSpells) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 2);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Set equippedSpells.
   */
  function setEquippedSpells(bytes32 characterId, uint256[] memory equippedSpells) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 2, EncodeArray.encode((equippedSpells)));
  }

  /**
   * @notice Set equippedSpells.
   */
  function _setEquippedSpells(bytes32 characterId, uint256[] memory equippedSpells) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 2, EncodeArray.encode((equippedSpells)));
  }

  /**
   * @notice Get the length of equippedSpells.
   */
  function lengthEquippedSpells(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 2);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of equippedSpells.
   */
  function _lengthEquippedSpells(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 2);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of equippedSpells.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemEquippedSpells(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 2, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Get an item of equippedSpells.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemEquippedSpells(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 2, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Push an element to equippedSpells.
   */
  function pushEquippedSpells(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 2, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to equippedSpells.
   */
  function _pushEquippedSpells(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 2, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from equippedSpells.
   */
  function popEquippedSpells(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 2, 32);
  }

  /**
   * @notice Pop an element from equippedSpells.
   */
  function _popEquippedSpells(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 2, 32);
  }

  /**
   * @notice Update an element of equippedSpells at `_index`.
   */
  function updateEquippedSpells(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 2, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of equippedSpells at `_index`.
   */
  function _updateEquippedSpells(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 2, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get equippedConsumables.
   */
  function getEquippedConsumables(bytes32 characterId) internal view returns (uint256[] memory equippedConsumables) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 3);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Get equippedConsumables.
   */
  function _getEquippedConsumables(bytes32 characterId) internal view returns (uint256[] memory equippedConsumables) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 3);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Set equippedConsumables.
   */
  function setEquippedConsumables(bytes32 characterId, uint256[] memory equippedConsumables) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 3, EncodeArray.encode((equippedConsumables)));
  }

  /**
   * @notice Set equippedConsumables.
   */
  function _setEquippedConsumables(bytes32 characterId, uint256[] memory equippedConsumables) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 3, EncodeArray.encode((equippedConsumables)));
  }

  /**
   * @notice Get the length of equippedConsumables.
   */
  function lengthEquippedConsumables(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 3);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of equippedConsumables.
   */
  function _lengthEquippedConsumables(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 3);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of equippedConsumables.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemEquippedConsumables(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 3, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Get an item of equippedConsumables.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemEquippedConsumables(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 3, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Push an element to equippedConsumables.
   */
  function pushEquippedConsumables(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 3, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to equippedConsumables.
   */
  function _pushEquippedConsumables(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 3, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from equippedConsumables.
   */
  function popEquippedConsumables(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 3, 32);
  }

  /**
   * @notice Pop an element from equippedConsumables.
   */
  function _popEquippedConsumables(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 3, 32);
  }

  /**
   * @notice Update an element of equippedConsumables at `_index`.
   */
  function updateEquippedConsumables(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 3, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of equippedConsumables at `_index`.
   */
  function _updateEquippedConsumables(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 3, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get equippedAccessories.
   */
  function getEquippedAccessories(bytes32 characterId) internal view returns (uint256[] memory equippedAccessories) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 4);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Get equippedAccessories.
   */
  function _getEquippedAccessories(bytes32 characterId) internal view returns (uint256[] memory equippedAccessories) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 4);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Set equippedAccessories.
   */
  function setEquippedAccessories(bytes32 characterId, uint256[] memory equippedAccessories) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 4, EncodeArray.encode((equippedAccessories)));
  }

  /**
   * @notice Set equippedAccessories.
   */
  function _setEquippedAccessories(bytes32 characterId, uint256[] memory equippedAccessories) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 4, EncodeArray.encode((equippedAccessories)));
  }

  /**
   * @notice Get the length of equippedAccessories.
   */
  function lengthEquippedAccessories(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 4);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of equippedAccessories.
   */
  function _lengthEquippedAccessories(bytes32 characterId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 4);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of equippedAccessories.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemEquippedAccessories(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 4, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Get an item of equippedAccessories.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemEquippedAccessories(bytes32 characterId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 4, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Push an element to equippedAccessories.
   */
  function pushEquippedAccessories(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 4, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to equippedAccessories.
   */
  function _pushEquippedAccessories(bytes32 characterId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 4, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from equippedAccessories.
   */
  function popEquippedAccessories(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 4, 32);
  }

  /**
   * @notice Pop an element from equippedAccessories.
   */
  function _popEquippedAccessories(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 4, 32);
  }

  /**
   * @notice Update an element of equippedAccessories at `_index`.
   */
  function updateEquippedAccessories(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 4, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of equippedAccessories at `_index`.
   */
  function _updateEquippedAccessories(bytes32 characterId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 4, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 characterId) internal view returns (CharacterEquipmentData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 characterId) internal view returns (CharacterEquipmentData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 characterId,
    int256 strBonus,
    int256 agiBonus,
    int256 intBonus,
    int256 hpBonus,
    int256 armor,
    uint256[] memory equippedArmor,
    uint256[] memory equippedWeapons,
    uint256[] memory equippedSpells,
    uint256[] memory equippedConsumables,
    uint256[] memory equippedAccessories
  ) internal {
    bytes memory _staticData = encodeStatic(strBonus, agiBonus, intBonus, hpBonus, armor);

    EncodedLengths _encodedLengths = encodeLengths(
      equippedArmor,
      equippedWeapons,
      equippedSpells,
      equippedConsumables,
      equippedAccessories
    );
    bytes memory _dynamicData = encodeDynamic(
      equippedArmor,
      equippedWeapons,
      equippedSpells,
      equippedConsumables,
      equippedAccessories
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 characterId,
    int256 strBonus,
    int256 agiBonus,
    int256 intBonus,
    int256 hpBonus,
    int256 armor,
    uint256[] memory equippedArmor,
    uint256[] memory equippedWeapons,
    uint256[] memory equippedSpells,
    uint256[] memory equippedConsumables,
    uint256[] memory equippedAccessories
  ) internal {
    bytes memory _staticData = encodeStatic(strBonus, agiBonus, intBonus, hpBonus, armor);

    EncodedLengths _encodedLengths = encodeLengths(
      equippedArmor,
      equippedWeapons,
      equippedSpells,
      equippedConsumables,
      equippedAccessories
    );
    bytes memory _dynamicData = encodeDynamic(
      equippedArmor,
      equippedWeapons,
      equippedSpells,
      equippedConsumables,
      equippedAccessories
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 characterId, CharacterEquipmentData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.strBonus,
      _table.agiBonus,
      _table.intBonus,
      _table.hpBonus,
      _table.armor
    );

    EncodedLengths _encodedLengths = encodeLengths(
      _table.equippedArmor,
      _table.equippedWeapons,
      _table.equippedSpells,
      _table.equippedConsumables,
      _table.equippedAccessories
    );
    bytes memory _dynamicData = encodeDynamic(
      _table.equippedArmor,
      _table.equippedWeapons,
      _table.equippedSpells,
      _table.equippedConsumables,
      _table.equippedAccessories
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 characterId, CharacterEquipmentData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.strBonus,
      _table.agiBonus,
      _table.intBonus,
      _table.hpBonus,
      _table.armor
    );

    EncodedLengths _encodedLengths = encodeLengths(
      _table.equippedArmor,
      _table.equippedWeapons,
      _table.equippedSpells,
      _table.equippedConsumables,
      _table.equippedAccessories
    );
    bytes memory _dynamicData = encodeDynamic(
      _table.equippedArmor,
      _table.equippedWeapons,
      _table.equippedSpells,
      _table.equippedConsumables,
      _table.equippedAccessories
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (int256 strBonus, int256 agiBonus, int256 intBonus, int256 hpBonus, int256 armor) {
    strBonus = (int256(uint256(Bytes.getBytes32(_blob, 0))));

    agiBonus = (int256(uint256(Bytes.getBytes32(_blob, 32))));

    intBonus = (int256(uint256(Bytes.getBytes32(_blob, 64))));

    hpBonus = (int256(uint256(Bytes.getBytes32(_blob, 96))));

    armor = (int256(uint256(Bytes.getBytes32(_blob, 128))));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256[] memory equippedArmor,
      uint256[] memory equippedWeapons,
      uint256[] memory equippedSpells,
      uint256[] memory equippedConsumables,
      uint256[] memory equippedAccessories
    )
  {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    equippedArmor = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint256());

    _start = _end;
    unchecked {
      _end += _encodedLengths.atIndex(1);
    }
    equippedWeapons = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint256());

    _start = _end;
    unchecked {
      _end += _encodedLengths.atIndex(2);
    }
    equippedSpells = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint256());

    _start = _end;
    unchecked {
      _end += _encodedLengths.atIndex(3);
    }
    equippedConsumables = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint256());

    _start = _end;
    unchecked {
      _end += _encodedLengths.atIndex(4);
    }
    equippedAccessories = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint256());
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (CharacterEquipmentData memory _table) {
    (_table.strBonus, _table.agiBonus, _table.intBonus, _table.hpBonus, _table.armor) = decodeStatic(_staticData);

    (
      _table.equippedArmor,
      _table.equippedWeapons,
      _table.equippedSpells,
      _table.equippedConsumables,
      _table.equippedAccessories
    ) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 characterId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    int256 strBonus,
    int256 agiBonus,
    int256 intBonus,
    int256 hpBonus,
    int256 armor
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(strBonus, agiBonus, intBonus, hpBonus, armor);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(
    uint256[] memory equippedArmor,
    uint256[] memory equippedWeapons,
    uint256[] memory equippedSpells,
    uint256[] memory equippedConsumables,
    uint256[] memory equippedAccessories
  ) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(
        equippedArmor.length * 32,
        equippedWeapons.length * 32,
        equippedSpells.length * 32,
        equippedConsumables.length * 32,
        equippedAccessories.length * 32
      );
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(
    uint256[] memory equippedArmor,
    uint256[] memory equippedWeapons,
    uint256[] memory equippedSpells,
    uint256[] memory equippedConsumables,
    uint256[] memory equippedAccessories
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        EncodeArray.encode((equippedArmor)),
        EncodeArray.encode((equippedWeapons)),
        EncodeArray.encode((equippedSpells)),
        EncodeArray.encode((equippedConsumables)),
        EncodeArray.encode((equippedAccessories))
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    int256 strBonus,
    int256 agiBonus,
    int256 intBonus,
    int256 hpBonus,
    int256 armor,
    uint256[] memory equippedArmor,
    uint256[] memory equippedWeapons,
    uint256[] memory equippedSpells,
    uint256[] memory equippedConsumables,
    uint256[] memory equippedAccessories
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(strBonus, agiBonus, intBonus, hpBonus, armor);

    EncodedLengths _encodedLengths = encodeLengths(
      equippedArmor,
      equippedWeapons,
      equippedSpells,
      equippedConsumables,
      equippedAccessories
    );
    bytes memory _dynamicData = encodeDynamic(
      equippedArmor,
      equippedWeapons,
      equippedSpells,
      equippedConsumables,
      equippedAccessories
    );

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 characterId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = characterId;

    return _keyTuple;
  }
}
