// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct GasStationSwapConfigData {
  address swapRouter;
  address weth;
  uint24 poolFee;
  address relayerAddress;
  uint256 goldPerGasCharge;
}

library GasStationSwapConfig {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "GasStationSwapCo", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462554400000000000000000000000047617353746174696f6e53776170436f);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x005f050014140314200000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, address, uint24, address, uint256)
  Schema constant _valueSchema = Schema.wrap(0x005f0500616102611f0000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "swapRouter";
    fieldNames[1] = "weth";
    fieldNames[2] = "poolFee";
    fieldNames[3] = "relayerAddress";
    fieldNames[4] = "goldPerGasCharge";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get swapRouter.
   */
  function getSwapRouter() internal view returns (address swapRouter) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get swapRouter.
   */
  function _getSwapRouter() internal view returns (address swapRouter) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set swapRouter.
   */
  function setSwapRouter(address swapRouter) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((swapRouter)), _fieldLayout);
  }

  /**
   * @notice Set swapRouter.
   */
  function _setSwapRouter(address swapRouter) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((swapRouter)), _fieldLayout);
  }

  /**
   * @notice Get weth.
   */
  function getWeth() internal view returns (address weth) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get weth.
   */
  function _getWeth() internal view returns (address weth) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set weth.
   */
  function setWeth(address weth) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((weth)), _fieldLayout);
  }

  /**
   * @notice Set weth.
   */
  function _setWeth(address weth) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((weth)), _fieldLayout);
  }

  /**
   * @notice Get poolFee.
   */
  function getPoolFee() internal view returns (uint24 poolFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint24(bytes3(_blob)));
  }

  /**
   * @notice Get poolFee.
   */
  function _getPoolFee() internal view returns (uint24 poolFee) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint24(bytes3(_blob)));
  }

  /**
   * @notice Set poolFee.
   */
  function setPoolFee(uint24 poolFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((poolFee)), _fieldLayout);
  }

  /**
   * @notice Set poolFee.
   */
  function _setPoolFee(uint24 poolFee) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((poolFee)), _fieldLayout);
  }

  /**
   * @notice Get relayerAddress.
   */
  function getRelayerAddress() internal view returns (address relayerAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get relayerAddress.
   */
  function _getRelayerAddress() internal view returns (address relayerAddress) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set relayerAddress.
   */
  function setRelayerAddress(address relayerAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((relayerAddress)), _fieldLayout);
  }

  /**
   * @notice Set relayerAddress.
   */
  function _setRelayerAddress(address relayerAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((relayerAddress)), _fieldLayout);
  }

  /**
   * @notice Get goldPerGasCharge.
   */
  function getGoldPerGasCharge() internal view returns (uint256 goldPerGasCharge) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get goldPerGasCharge.
   */
  function _getGoldPerGasCharge() internal view returns (uint256 goldPerGasCharge) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set goldPerGasCharge.
   */
  function setGoldPerGasCharge(uint256 goldPerGasCharge) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((goldPerGasCharge)), _fieldLayout);
  }

  /**
   * @notice Set goldPerGasCharge.
   */
  function _setGoldPerGasCharge(uint256 goldPerGasCharge) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((goldPerGasCharge)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (GasStationSwapConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (GasStationSwapConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address swapRouter,
    address weth,
    uint24 poolFee,
    address relayerAddress,
    uint256 goldPerGasCharge
  ) internal {
    bytes memory _staticData = encodeStatic(swapRouter, weth, poolFee, relayerAddress, goldPerGasCharge);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address swapRouter,
    address weth,
    uint24 poolFee,
    address relayerAddress,
    uint256 goldPerGasCharge
  ) internal {
    bytes memory _staticData = encodeStatic(swapRouter, weth, poolFee, relayerAddress, goldPerGasCharge);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(GasStationSwapConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.swapRouter,
      _table.weth,
      _table.poolFee,
      _table.relayerAddress,
      _table.goldPerGasCharge
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(GasStationSwapConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.swapRouter,
      _table.weth,
      _table.poolFee,
      _table.relayerAddress,
      _table.goldPerGasCharge
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (address swapRouter, address weth, uint24 poolFee, address relayerAddress, uint256 goldPerGasCharge)
  {
    swapRouter = (address(Bytes.getBytes20(_blob, 0)));

    weth = (address(Bytes.getBytes20(_blob, 20)));

    poolFee = (uint24(Bytes.getBytes3(_blob, 40)));

    relayerAddress = (address(Bytes.getBytes20(_blob, 43)));

    goldPerGasCharge = (uint256(Bytes.getBytes32(_blob, 63)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (GasStationSwapConfigData memory _table) {
    (_table.swapRouter, _table.weth, _table.poolFee, _table.relayerAddress, _table.goldPerGasCharge) = decodeStatic(
      _staticData
    );
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address swapRouter,
    address weth,
    uint24 poolFee,
    address relayerAddress,
    uint256 goldPerGasCharge
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(swapRouter, weth, poolFee, relayerAddress, goldPerGasCharge);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address swapRouter,
    address weth,
    uint24 poolFee,
    address relayerAddress,
    uint256 goldPerGasCharge
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(swapRouter, weth, poolFee, relayerAddress, goldPerGasCharge);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
