// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct MagicAttackStatsData {
  int256 attackModifierBonus;
  int256 bonusDamage;
  int256 chitChanceBonus;
  int256 minLevel;
  bytes32[] statusEffects;
}

library MagicAttackStats {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "MagicAttackStats", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746255440000000000000000000000004d6167696341747461636b5374617473);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0080040120202020000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (int256, int256, int256, int256, bytes32[])
  Schema constant _valueSchema = Schema.wrap(0x008004013f3f3f3fc10000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "actionId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "attackModifierBonus";
    fieldNames[1] = "bonusDamage";
    fieldNames[2] = "chitChanceBonus";
    fieldNames[3] = "minLevel";
    fieldNames[4] = "statusEffects";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get attackModifierBonus.
   */
  function getAttackModifierBonus(bytes32 actionId) internal view returns (int256 attackModifierBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get attackModifierBonus.
   */
  function _getAttackModifierBonus(bytes32 actionId) internal view returns (int256 attackModifierBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set attackModifierBonus.
   */
  function setAttackModifierBonus(bytes32 actionId, int256 attackModifierBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((attackModifierBonus)), _fieldLayout);
  }

  /**
   * @notice Set attackModifierBonus.
   */
  function _setAttackModifierBonus(bytes32 actionId, int256 attackModifierBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((attackModifierBonus)), _fieldLayout);
  }

  /**
   * @notice Get bonusDamage.
   */
  function getBonusDamage(bytes32 actionId) internal view returns (int256 bonusDamage) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get bonusDamage.
   */
  function _getBonusDamage(bytes32 actionId) internal view returns (int256 bonusDamage) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set bonusDamage.
   */
  function setBonusDamage(bytes32 actionId, int256 bonusDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((bonusDamage)), _fieldLayout);
  }

  /**
   * @notice Set bonusDamage.
   */
  function _setBonusDamage(bytes32 actionId, int256 bonusDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((bonusDamage)), _fieldLayout);
  }

  /**
   * @notice Get chitChanceBonus.
   */
  function getChitChanceBonus(bytes32 actionId) internal view returns (int256 chitChanceBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get chitChanceBonus.
   */
  function _getChitChanceBonus(bytes32 actionId) internal view returns (int256 chitChanceBonus) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set chitChanceBonus.
   */
  function setChitChanceBonus(bytes32 actionId, int256 chitChanceBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((chitChanceBonus)), _fieldLayout);
  }

  /**
   * @notice Set chitChanceBonus.
   */
  function _setChitChanceBonus(bytes32 actionId, int256 chitChanceBonus) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((chitChanceBonus)), _fieldLayout);
  }

  /**
   * @notice Get minLevel.
   */
  function getMinLevel(bytes32 actionId) internal view returns (int256 minLevel) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get minLevel.
   */
  function _getMinLevel(bytes32 actionId) internal view returns (int256 minLevel) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set minLevel.
   */
  function setMinLevel(bytes32 actionId, int256 minLevel) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((minLevel)), _fieldLayout);
  }

  /**
   * @notice Set minLevel.
   */
  function _setMinLevel(bytes32 actionId, int256 minLevel) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((minLevel)), _fieldLayout);
  }

  /**
   * @notice Get statusEffects.
   */
  function getStatusEffects(bytes32 actionId) internal view returns (bytes32[] memory statusEffects) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get statusEffects.
   */
  function _getStatusEffects(bytes32 actionId) internal view returns (bytes32[] memory statusEffects) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Set statusEffects.
   */
  function setStatusEffects(bytes32 actionId, bytes32[] memory statusEffects) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((statusEffects)));
  }

  /**
   * @notice Set statusEffects.
   */
  function _setStatusEffects(bytes32 actionId, bytes32[] memory statusEffects) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((statusEffects)));
  }

  /**
   * @notice Get the length of statusEffects.
   */
  function lengthStatusEffects(bytes32 actionId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of statusEffects.
   */
  function _lengthStatusEffects(bytes32 actionId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of statusEffects.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemStatusEffects(bytes32 actionId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of statusEffects.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemStatusEffects(bytes32 actionId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Push an element to statusEffects.
   */
  function pushStatusEffects(bytes32 actionId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to statusEffects.
   */
  function _pushStatusEffects(bytes32 actionId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from statusEffects.
   */
  function popStatusEffects(bytes32 actionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from statusEffects.
   */
  function _popStatusEffects(bytes32 actionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Update an element of statusEffects at `_index`.
   */
  function updateStatusEffects(bytes32 actionId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of statusEffects at `_index`.
   */
  function _updateStatusEffects(bytes32 actionId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 actionId) internal view returns (MagicAttackStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 actionId) internal view returns (MagicAttackStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 actionId,
    int256 attackModifierBonus,
    int256 bonusDamage,
    int256 chitChanceBonus,
    int256 minLevel,
    bytes32[] memory statusEffects
  ) internal {
    bytes memory _staticData = encodeStatic(attackModifierBonus, bonusDamage, chitChanceBonus, minLevel);

    EncodedLengths _encodedLengths = encodeLengths(statusEffects);
    bytes memory _dynamicData = encodeDynamic(statusEffects);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 actionId,
    int256 attackModifierBonus,
    int256 bonusDamage,
    int256 chitChanceBonus,
    int256 minLevel,
    bytes32[] memory statusEffects
  ) internal {
    bytes memory _staticData = encodeStatic(attackModifierBonus, bonusDamage, chitChanceBonus, minLevel);

    EncodedLengths _encodedLengths = encodeLengths(statusEffects);
    bytes memory _dynamicData = encodeDynamic(statusEffects);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 actionId, MagicAttackStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.attackModifierBonus,
      _table.bonusDamage,
      _table.chitChanceBonus,
      _table.minLevel
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.statusEffects);
    bytes memory _dynamicData = encodeDynamic(_table.statusEffects);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 actionId, MagicAttackStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.attackModifierBonus,
      _table.bonusDamage,
      _table.chitChanceBonus,
      _table.minLevel
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.statusEffects);
    bytes memory _dynamicData = encodeDynamic(_table.statusEffects);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (int256 attackModifierBonus, int256 bonusDamage, int256 chitChanceBonus, int256 minLevel) {
    attackModifierBonus = (int256(uint256(Bytes.getBytes32(_blob, 0))));

    bonusDamage = (int256(uint256(Bytes.getBytes32(_blob, 32))));

    chitChanceBonus = (int256(uint256(Bytes.getBytes32(_blob, 64))));

    minLevel = (int256(uint256(Bytes.getBytes32(_blob, 96))));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (bytes32[] memory statusEffects) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    statusEffects = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_bytes32());
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (MagicAttackStatsData memory _table) {
    (_table.attackModifierBonus, _table.bonusDamage, _table.chitChanceBonus, _table.minLevel) = decodeStatic(
      _staticData
    );

    (_table.statusEffects) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 actionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 actionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    int256 attackModifierBonus,
    int256 bonusDamage,
    int256 chitChanceBonus,
    int256 minLevel
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(attackModifierBonus, bonusDamage, chitChanceBonus, minLevel);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(bytes32[] memory statusEffects) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(statusEffects.length * 32);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(bytes32[] memory statusEffects) internal pure returns (bytes memory) {
    return abi.encodePacked(EncodeArray.encode((statusEffects)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    int256 attackModifierBonus,
    int256 bonusDamage,
    int256 chitChanceBonus,
    int256 minLevel,
    bytes32[] memory statusEffects
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(attackModifierBonus, bonusDamage, chitChanceBonus, minLevel);

    EncodedLengths _encodedLengths = encodeLengths(statusEffects);
    bytes memory _dynamicData = encodeDynamic(statusEffects);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 actionId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = actionId;

    return _keyTuple;
  }
}
