// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { Classes } from "./../common.sol";

struct MonsterStatsData {
  uint256 agility;
  uint256 armor;
  Classes class;
  uint256 experience;
  uint256 hitPoints;
  uint256 intelligence;
  uint256 level;
  uint256 strength;
  uint256[] inventory;
}

library MonsterStats {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "MonsterStats", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746255440000000000000000000000004d6f6e73746572537461747300000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00e1080120200120202020200000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256)
  Schema constant _keySchema = Schema.wrap(0x002001001f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint8, uint256, uint256, uint256, uint256, uint256, uint256[])
  Schema constant _valueSchema = Schema.wrap(0x00e108011f1f001f1f1f1f1f8100000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "mobId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](9);
    fieldNames[0] = "agility";
    fieldNames[1] = "armor";
    fieldNames[2] = "class";
    fieldNames[3] = "experience";
    fieldNames[4] = "hitPoints";
    fieldNames[5] = "intelligence";
    fieldNames[6] = "level";
    fieldNames[7] = "strength";
    fieldNames[8] = "inventory";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get agility.
   */
  function getAgility(uint256 mobId) internal view returns (uint256 agility) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get agility.
   */
  function _getAgility(uint256 mobId) internal view returns (uint256 agility) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set agility.
   */
  function setAgility(uint256 mobId, uint256 agility) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((agility)), _fieldLayout);
  }

  /**
   * @notice Set agility.
   */
  function _setAgility(uint256 mobId, uint256 agility) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((agility)), _fieldLayout);
  }

  /**
   * @notice Get armor.
   */
  function getArmor(uint256 mobId) internal view returns (uint256 armor) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get armor.
   */
  function _getArmor(uint256 mobId) internal view returns (uint256 armor) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set armor.
   */
  function setArmor(uint256 mobId, uint256 armor) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((armor)), _fieldLayout);
  }

  /**
   * @notice Set armor.
   */
  function _setArmor(uint256 mobId, uint256 armor) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((armor)), _fieldLayout);
  }

  /**
   * @notice Get class.
   */
  function getClass(uint256 mobId) internal view returns (Classes class) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return Classes(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get class.
   */
  function _getClass(uint256 mobId) internal view returns (Classes class) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return Classes(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set class.
   */
  function setClass(uint256 mobId, Classes class) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked(uint8(class)), _fieldLayout);
  }

  /**
   * @notice Set class.
   */
  function _setClass(uint256 mobId, Classes class) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked(uint8(class)), _fieldLayout);
  }

  /**
   * @notice Get experience.
   */
  function getExperience(uint256 mobId) internal view returns (uint256 experience) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get experience.
   */
  function _getExperience(uint256 mobId) internal view returns (uint256 experience) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set experience.
   */
  function setExperience(uint256 mobId, uint256 experience) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((experience)), _fieldLayout);
  }

  /**
   * @notice Set experience.
   */
  function _setExperience(uint256 mobId, uint256 experience) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((experience)), _fieldLayout);
  }

  /**
   * @notice Get hitPoints.
   */
  function getHitPoints(uint256 mobId) internal view returns (uint256 hitPoints) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get hitPoints.
   */
  function _getHitPoints(uint256 mobId) internal view returns (uint256 hitPoints) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set hitPoints.
   */
  function setHitPoints(uint256 mobId, uint256 hitPoints) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((hitPoints)), _fieldLayout);
  }

  /**
   * @notice Set hitPoints.
   */
  function _setHitPoints(uint256 mobId, uint256 hitPoints) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((hitPoints)), _fieldLayout);
  }

  /**
   * @notice Get intelligence.
   */
  function getIntelligence(uint256 mobId) internal view returns (uint256 intelligence) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get intelligence.
   */
  function _getIntelligence(uint256 mobId) internal view returns (uint256 intelligence) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set intelligence.
   */
  function setIntelligence(uint256 mobId, uint256 intelligence) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((intelligence)), _fieldLayout);
  }

  /**
   * @notice Set intelligence.
   */
  function _setIntelligence(uint256 mobId, uint256 intelligence) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((intelligence)), _fieldLayout);
  }

  /**
   * @notice Get level.
   */
  function getLevel(uint256 mobId) internal view returns (uint256 level) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get level.
   */
  function _getLevel(uint256 mobId) internal view returns (uint256 level) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set level.
   */
  function setLevel(uint256 mobId, uint256 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((level)), _fieldLayout);
  }

  /**
   * @notice Set level.
   */
  function _setLevel(uint256 mobId, uint256 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((level)), _fieldLayout);
  }

  /**
   * @notice Get strength.
   */
  function getStrength(uint256 mobId) internal view returns (uint256 strength) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get strength.
   */
  function _getStrength(uint256 mobId) internal view returns (uint256 strength) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set strength.
   */
  function setStrength(uint256 mobId, uint256 strength) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((strength)), _fieldLayout);
  }

  /**
   * @notice Set strength.
   */
  function _setStrength(uint256 mobId, uint256 strength) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((strength)), _fieldLayout);
  }

  /**
   * @notice Get inventory.
   */
  function getInventory(uint256 mobId) internal view returns (uint256[] memory inventory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Get inventory.
   */
  function _getInventory(uint256 mobId) internal view returns (uint256[] memory inventory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Set inventory.
   */
  function setInventory(uint256 mobId, uint256[] memory inventory) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((inventory)));
  }

  /**
   * @notice Set inventory.
   */
  function _setInventory(uint256 mobId, uint256[] memory inventory) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((inventory)));
  }

  /**
   * @notice Get the length of inventory.
   */
  function lengthInventory(uint256 mobId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of inventory.
   */
  function _lengthInventory(uint256 mobId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of inventory.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemInventory(uint256 mobId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Get an item of inventory.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemInventory(uint256 mobId, uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Push an element to inventory.
   */
  function pushInventory(uint256 mobId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to inventory.
   */
  function _pushInventory(uint256 mobId, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from inventory.
   */
  function popInventory(uint256 mobId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from inventory.
   */
  function _popInventory(uint256 mobId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Update an element of inventory at `_index`.
   */
  function updateInventory(uint256 mobId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of inventory at `_index`.
   */
  function _updateInventory(uint256 mobId, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(uint256 mobId) internal view returns (MonsterStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint256 mobId) internal view returns (MonsterStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 mobId,
    uint256 agility,
    uint256 armor,
    Classes class,
    uint256 experience,
    uint256 hitPoints,
    uint256 intelligence,
    uint256 level,
    uint256 strength,
    uint256[] memory inventory
  ) internal {
    bytes memory _staticData = encodeStatic(
      agility,
      armor,
      class,
      experience,
      hitPoints,
      intelligence,
      level,
      strength
    );

    EncodedLengths _encodedLengths = encodeLengths(inventory);
    bytes memory _dynamicData = encodeDynamic(inventory);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 mobId,
    uint256 agility,
    uint256 armor,
    Classes class,
    uint256 experience,
    uint256 hitPoints,
    uint256 intelligence,
    uint256 level,
    uint256 strength,
    uint256[] memory inventory
  ) internal {
    bytes memory _staticData = encodeStatic(
      agility,
      armor,
      class,
      experience,
      hitPoints,
      intelligence,
      level,
      strength
    );

    EncodedLengths _encodedLengths = encodeLengths(inventory);
    bytes memory _dynamicData = encodeDynamic(inventory);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 mobId, MonsterStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.agility,
      _table.armor,
      _table.class,
      _table.experience,
      _table.hitPoints,
      _table.intelligence,
      _table.level,
      _table.strength
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.inventory);
    bytes memory _dynamicData = encodeDynamic(_table.inventory);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 mobId, MonsterStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.agility,
      _table.armor,
      _table.class,
      _table.experience,
      _table.hitPoints,
      _table.intelligence,
      _table.level,
      _table.strength
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.inventory);
    bytes memory _dynamicData = encodeDynamic(_table.inventory);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256 agility,
      uint256 armor,
      Classes class,
      uint256 experience,
      uint256 hitPoints,
      uint256 intelligence,
      uint256 level,
      uint256 strength
    )
  {
    agility = (uint256(Bytes.getBytes32(_blob, 0)));

    armor = (uint256(Bytes.getBytes32(_blob, 32)));

    class = Classes(uint8(Bytes.getBytes1(_blob, 64)));

    experience = (uint256(Bytes.getBytes32(_blob, 65)));

    hitPoints = (uint256(Bytes.getBytes32(_blob, 97)));

    intelligence = (uint256(Bytes.getBytes32(_blob, 129)));

    level = (uint256(Bytes.getBytes32(_blob, 161)));

    strength = (uint256(Bytes.getBytes32(_blob, 193)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (uint256[] memory inventory) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    inventory = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint256());
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (MonsterStatsData memory _table) {
    (
      _table.agility,
      _table.armor,
      _table.class,
      _table.experience,
      _table.hitPoints,
      _table.intelligence,
      _table.level,
      _table.strength
    ) = decodeStatic(_staticData);

    (_table.inventory) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 mobId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 mobId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 agility,
    uint256 armor,
    Classes class,
    uint256 experience,
    uint256 hitPoints,
    uint256 intelligence,
    uint256 level,
    uint256 strength
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(agility, armor, class, experience, hitPoints, intelligence, level, strength);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(uint256[] memory inventory) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(inventory.length * 32);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(uint256[] memory inventory) internal pure returns (bytes memory) {
    return abi.encodePacked(EncodeArray.encode((inventory)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 agility,
    uint256 armor,
    Classes class,
    uint256 experience,
    uint256 hitPoints,
    uint256 intelligence,
    uint256 level,
    uint256 strength,
    uint256[] memory inventory
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      agility,
      armor,
      class,
      experience,
      hitPoints,
      intelligence,
      level,
      strength
    );

    EncodedLengths _encodedLengths = encodeLengths(inventory);
    bytes memory _dynamicData = encodeDynamic(inventory);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 mobId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(mobId));

    return _keyTuple;
  }
}
