// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import {IStore} from "@latticexyz/store/src/IStore.sol";
import {StoreSwitch} from "@latticexyz/store/src/StoreSwitch.sol";
import {StoreCore} from "@latticexyz/store/src/StoreCore.sol";
import {Bytes} from "@latticexyz/store/src/Bytes.sol";
import {Memory} from "@latticexyz/store/src/Memory.sol";
import {SliceLib} from "@latticexyz/store/src/Slice.sol";
import {EncodeArray} from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import {FieldLayout} from "@latticexyz/store/src/FieldLayout.sol";
import {Schema} from "@latticexyz/store/src/Schema.sol";
import {EncodedLengths, EncodedLengthsLib} from "@latticexyz/store/src/EncodedLengths.sol";
import {ResourceId} from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import {TokenType} from "./../common.sol";

struct OffersData {
    TokenType tokenType;
    address token;
    uint256 identifier;
    uint256 amount;
}

library Offers {
    // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "Offers", typeId: RESOURCE_TABLE });`
    ResourceId constant _tableId = ResourceId.wrap(0x746255440000000000000000000000004f666665727300000000000000000000);

    FieldLayout constant _fieldLayout =
        FieldLayout.wrap(0x0055040001142020000000000000000000000000000000000000000000000000);

    // Hex-encoded key schema of (bytes32)
    Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
    // Hex-encoded value schema of (uint8, address, uint256, uint256)
    Schema constant _valueSchema = Schema.wrap(0x0055040000611f1f000000000000000000000000000000000000000000000000);

    /**
     * @notice Get the table's key field names.
     * @return keyNames An array of strings with the names of key fields.
     */
    function getKeyNames() internal pure returns (string[] memory keyNames) {
        keyNames = new string[](1);
        keyNames[0] = "orderHash";
    }

    /**
     * @notice Get the table's value field names.
     * @return fieldNames An array of strings with the names of value fields.
     */
    function getFieldNames() internal pure returns (string[] memory fieldNames) {
        fieldNames = new string[](4);
        fieldNames[0] = "tokenType";
        fieldNames[1] = "token";
        fieldNames[2] = "identifier";
        fieldNames[3] = "amount";
    }

    /**
     * @notice Register the table with its config.
     */
    function register() internal {
        StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
    }

    /**
     * @notice Register the table with its config.
     */
    function _register() internal {
        StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
    }

    /**
     * @notice Get tokenType.
     */
    function getTokenType(bytes32 orderHash) internal view returns (TokenType tokenType) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
        return TokenType(uint8(bytes1(_blob)));
    }

    /**
     * @notice Get tokenType.
     */
    function _getTokenType(bytes32 orderHash) internal view returns (TokenType tokenType) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
        return TokenType(uint8(bytes1(_blob)));
    }

    /**
     * @notice Set tokenType.
     */
    function setTokenType(bytes32 orderHash, TokenType tokenType) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked(uint8(tokenType)), _fieldLayout);
    }

    /**
     * @notice Set tokenType.
     */
    function _setTokenType(bytes32 orderHash, TokenType tokenType) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked(uint8(tokenType)), _fieldLayout);
    }

    /**
     * @notice Get token.
     */
    function getToken(bytes32 orderHash) internal view returns (address token) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
        return (address(bytes20(_blob)));
    }

    /**
     * @notice Get token.
     */
    function _getToken(bytes32 orderHash) internal view returns (address token) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
        return (address(bytes20(_blob)));
    }

    /**
     * @notice Set token.
     */
    function setToken(bytes32 orderHash, address token) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((token)), _fieldLayout);
    }

    /**
     * @notice Set token.
     */
    function _setToken(bytes32 orderHash, address token) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((token)), _fieldLayout);
    }

    /**
     * @notice Get identifier.
     */
    function getIdentifier(bytes32 orderHash) internal view returns (uint256 identifier) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
        return (uint256(bytes32(_blob)));
    }

    /**
     * @notice Get identifier.
     */
    function _getIdentifier(bytes32 orderHash) internal view returns (uint256 identifier) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
        return (uint256(bytes32(_blob)));
    }

    /**
     * @notice Set identifier.
     */
    function setIdentifier(bytes32 orderHash, uint256 identifier) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((identifier)), _fieldLayout);
    }

    /**
     * @notice Set identifier.
     */
    function _setIdentifier(bytes32 orderHash, uint256 identifier) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((identifier)), _fieldLayout);
    }

    /**
     * @notice Get amount.
     */
    function getAmount(bytes32 orderHash) internal view returns (uint256 amount) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
        return (uint256(bytes32(_blob)));
    }

    /**
     * @notice Get amount.
     */
    function _getAmount(bytes32 orderHash) internal view returns (uint256 amount) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
        return (uint256(bytes32(_blob)));
    }

    /**
     * @notice Set amount.
     */
    function setAmount(bytes32 orderHash, uint256 amount) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((amount)), _fieldLayout);
    }

    /**
     * @notice Set amount.
     */
    function _setAmount(bytes32 orderHash, uint256 amount) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((amount)), _fieldLayout);
    }

    /**
     * @notice Get the full data.
     */
    function get(bytes32 orderHash) internal view returns (OffersData memory _table) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) =
            StoreSwitch.getRecord(_tableId, _keyTuple, _fieldLayout);
        return decode(_staticData, _encodedLengths, _dynamicData);
    }

    /**
     * @notice Get the full data.
     */
    function _get(bytes32 orderHash) internal view returns (OffersData memory _table) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) =
            StoreCore.getRecord(_tableId, _keyTuple, _fieldLayout);
        return decode(_staticData, _encodedLengths, _dynamicData);
    }

    /**
     * @notice Set the full data using individual values.
     */
    function set(bytes32 orderHash, TokenType tokenType, address token, uint256 identifier, uint256 amount) internal {
        bytes memory _staticData = encodeStatic(tokenType, token, identifier, amount);

        EncodedLengths _encodedLengths;
        bytes memory _dynamicData;

        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
    }

    /**
     * @notice Set the full data using individual values.
     */
    function _set(bytes32 orderHash, TokenType tokenType, address token, uint256 identifier, uint256 amount) internal {
        bytes memory _staticData = encodeStatic(tokenType, token, identifier, amount);

        EncodedLengths _encodedLengths;
        bytes memory _dynamicData;

        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
    }

    /**
     * @notice Set the full data using the data struct.
     */
    function set(bytes32 orderHash, OffersData memory _table) internal {
        bytes memory _staticData = encodeStatic(_table.tokenType, _table.token, _table.identifier, _table.amount);

        EncodedLengths _encodedLengths;
        bytes memory _dynamicData;

        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
    }

    /**
     * @notice Set the full data using the data struct.
     */
    function _set(bytes32 orderHash, OffersData memory _table) internal {
        bytes memory _staticData = encodeStatic(_table.tokenType, _table.token, _table.identifier, _table.amount);

        EncodedLengths _encodedLengths;
        bytes memory _dynamicData;

        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
    }

    /**
     * @notice Decode the tightly packed blob of static data using this table's field layout.
     */
    function decodeStatic(bytes memory _blob)
        internal
        pure
        returns (TokenType tokenType, address token, uint256 identifier, uint256 amount)
    {
        tokenType = TokenType(uint8(Bytes.getBytes1(_blob, 0)));

        token = (address(Bytes.getBytes20(_blob, 1)));

        identifier = (uint256(Bytes.getBytes32(_blob, 21)));

        amount = (uint256(Bytes.getBytes32(_blob, 53)));
    }

    /**
     * @notice Decode the tightly packed blobs using this table's field layout.
     * @param _staticData Tightly packed static fields.
     *
     *
     */
    function decode(bytes memory _staticData, EncodedLengths, bytes memory)
        internal
        pure
        returns (OffersData memory _table)
    {
        (_table.tokenType, _table.token, _table.identifier, _table.amount) = decodeStatic(_staticData);
    }

    /**
     * @notice Delete all data for given keys.
     */
    function deleteRecord(bytes32 orderHash) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreSwitch.deleteRecord(_tableId, _keyTuple);
    }

    /**
     * @notice Delete all data for given keys.
     */
    function _deleteRecord(bytes32 orderHash) internal {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
    }

    /**
     * @notice Tightly pack static (fixed length) data using this table's schema.
     * @return The static data, encoded into a sequence of bytes.
     */
    function encodeStatic(TokenType tokenType, address token, uint256 identifier, uint256 amount)
        internal
        pure
        returns (bytes memory)
    {
        return abi.encodePacked(tokenType, token, identifier, amount);
    }

    /**
     * @notice Encode all of a record's fields.
     * @return The static (fixed length) data, encoded into a sequence of bytes.
     * @return The lengths of the dynamic fields (packed into a single bytes32 value).
     * @return The dynamic (variable length) data, encoded into a sequence of bytes.
     */
    function encode(TokenType tokenType, address token, uint256 identifier, uint256 amount)
        internal
        pure
        returns (bytes memory, EncodedLengths, bytes memory)
    {
        bytes memory _staticData = encodeStatic(tokenType, token, identifier, amount);

        EncodedLengths _encodedLengths;
        bytes memory _dynamicData;

        return (_staticData, _encodedLengths, _dynamicData);
    }

    /**
     * @notice Encode keys as a bytes32 array using this table's field layout.
     */
    function encodeKeyTuple(bytes32 orderHash) internal pure returns (bytes32[] memory) {
        bytes32[] memory _keyTuple = new bytes32[](1);
        _keyTuple[0] = orderHash;

        return _keyTuple;
    }
}
