// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { RngRequestType } from "../common.sol";

struct RngLogsData {
  uint64 sequenceNumber;
  RngRequestType requestType;
  uint256 randomNumber;
  bytes32 userRandomNumber;
  bytes data;
}

library RngLogs {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "RngLogs", typeId: RESOURCE_OFFCHAIN_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x6f745544000000000000000000000000526e674c6f6773000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0049040108012020000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256)
  Schema constant _keySchema = Schema.wrap(0x002001001f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint64, uint8, uint256, bytes32, bytes)
  Schema constant _valueSchema = Schema.wrap(0x0049040107001f5fc40000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "requestId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "sequenceNumber";
    fieldNames[1] = "requestType";
    fieldNames[2] = "randomNumber";
    fieldNames[3] = "userRandomNumber";
    fieldNames[4] = "data";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Set sequenceNumber.
   */
  function setSequenceNumber(uint256 requestId, uint64 sequenceNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((sequenceNumber)), _fieldLayout);
  }

  /**
   * @notice Set sequenceNumber.
   */
  function _setSequenceNumber(uint256 requestId, uint64 sequenceNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((sequenceNumber)), _fieldLayout);
  }

  /**
   * @notice Set requestType.
   */
  function setRequestType(uint256 requestId, RngRequestType requestType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(requestType)), _fieldLayout);
  }

  /**
   * @notice Set requestType.
   */
  function _setRequestType(uint256 requestId, RngRequestType requestType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(requestType)), _fieldLayout);
  }

  /**
   * @notice Set randomNumber.
   */
  function setRandomNumber(uint256 requestId, uint256 randomNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((randomNumber)), _fieldLayout);
  }

  /**
   * @notice Set randomNumber.
   */
  function _setRandomNumber(uint256 requestId, uint256 randomNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((randomNumber)), _fieldLayout);
  }

  /**
   * @notice Set userRandomNumber.
   */
  function setUserRandomNumber(uint256 requestId, bytes32 userRandomNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((userRandomNumber)), _fieldLayout);
  }

  /**
   * @notice Set userRandomNumber.
   */
  function _setUserRandomNumber(uint256 requestId, bytes32 userRandomNumber) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((userRandomNumber)), _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 requestId,
    uint64 sequenceNumber,
    RngRequestType requestType,
    uint256 randomNumber,
    bytes32 userRandomNumber,
    bytes memory data
  ) internal {
    bytes memory _staticData = encodeStatic(sequenceNumber, requestType, randomNumber, userRandomNumber);

    EncodedLengths _encodedLengths = encodeLengths(data);
    bytes memory _dynamicData = encodeDynamic(data);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 requestId,
    uint64 sequenceNumber,
    RngRequestType requestType,
    uint256 randomNumber,
    bytes32 userRandomNumber,
    bytes memory data
  ) internal {
    bytes memory _staticData = encodeStatic(sequenceNumber, requestType, randomNumber, userRandomNumber);

    EncodedLengths _encodedLengths = encodeLengths(data);
    bytes memory _dynamicData = encodeDynamic(data);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 requestId, RngLogsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.sequenceNumber,
      _table.requestType,
      _table.randomNumber,
      _table.userRandomNumber
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.data);
    bytes memory _dynamicData = encodeDynamic(_table.data);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 requestId, RngLogsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.sequenceNumber,
      _table.requestType,
      _table.randomNumber,
      _table.userRandomNumber
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.data);
    bytes memory _dynamicData = encodeDynamic(_table.data);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (uint64 sequenceNumber, RngRequestType requestType, uint256 randomNumber, bytes32 userRandomNumber)
  {
    sequenceNumber = (uint64(Bytes.getBytes8(_blob, 0)));

    requestType = RngRequestType(uint8(Bytes.getBytes1(_blob, 8)));

    randomNumber = (uint256(Bytes.getBytes32(_blob, 9)));

    userRandomNumber = (Bytes.getBytes32(_blob, 41));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(EncodedLengths _encodedLengths, bytes memory _blob) internal pure returns (bytes memory data) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    data = (bytes(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (RngLogsData memory _table) {
    (_table.sequenceNumber, _table.requestType, _table.randomNumber, _table.userRandomNumber) = decodeStatic(
      _staticData
    );

    (_table.data) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 requestId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 requestId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint64 sequenceNumber,
    RngRequestType requestType,
    uint256 randomNumber,
    bytes32 userRandomNumber
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(sequenceNumber, requestType, randomNumber, userRandomNumber);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(bytes memory data) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(data).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(bytes memory data) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((data)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint64 sequenceNumber,
    RngRequestType requestType,
    uint256 randomNumber,
    bytes32 userRandomNumber,
    bytes memory data
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(sequenceNumber, requestType, randomNumber, userRandomNumber);

    EncodedLengths _encodedLengths = encodeLengths(data);
    bytes memory _dynamicData = encodeDynamic(data);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 requestId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(requestId));

    return _keyTuple;
  }
}
