// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { SkillType } from "./../common.sol";

struct SkillsData {
  SkillType skillType;
  bytes skillStats;
}

library Skills {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "Skills", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74625544000000000000000000000000536b696c6c7300000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0001010101000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8, bytes)
  Schema constant _valueSchema = Schema.wrap(0x0001010100c40000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "skillId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "skillType";
    fieldNames[1] = "skillStats";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get skillType.
   */
  function getSkillType(bytes32 skillId) internal view returns (SkillType skillType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return SkillType(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get skillType.
   */
  function _getSkillType(bytes32 skillId) internal view returns (SkillType skillType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return SkillType(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set skillType.
   */
  function setSkillType(bytes32 skillId, SkillType skillType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked(uint8(skillType)), _fieldLayout);
  }

  /**
   * @notice Set skillType.
   */
  function _setSkillType(bytes32 skillId, SkillType skillType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked(uint8(skillType)), _fieldLayout);
  }

  /**
   * @notice Get skillStats.
   */
  function getSkillStats(bytes32 skillId) internal view returns (bytes memory skillStats) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (bytes(_blob));
  }

  /**
   * @notice Get skillStats.
   */
  function _getSkillStats(bytes32 skillId) internal view returns (bytes memory skillStats) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (bytes(_blob));
  }

  /**
   * @notice Set skillStats.
   */
  function setSkillStats(bytes32 skillId, bytes memory skillStats) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((skillStats)));
  }

  /**
   * @notice Set skillStats.
   */
  function _setSkillStats(bytes32 skillId, bytes memory skillStats) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((skillStats)));
  }

  /**
   * @notice Get the length of skillStats.
   */
  function lengthSkillStats(bytes32 skillId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of skillStats.
   */
  function _lengthSkillStats(bytes32 skillId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of skillStats.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemSkillStats(bytes32 skillId, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (bytes(_blob));
    }
  }

  /**
   * @notice Get an item of skillStats.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemSkillStats(bytes32 skillId, uint256 _index) internal view returns (bytes memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (bytes(_blob));
    }
  }

  /**
   * @notice Push a slice to skillStats.
   */
  function pushSkillStats(bytes32 skillId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to skillStats.
   */
  function _pushSkillStats(bytes32 skillId, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from skillStats.
   */
  function popSkillStats(bytes32 skillId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from skillStats.
   */
  function _popSkillStats(bytes32 skillId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of skillStats at `_index`.
   */
  function updateSkillStats(bytes32 skillId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of skillStats at `_index`.
   */
  function _updateSkillStats(bytes32 skillId, uint256 _index, bytes memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 skillId) internal view returns (SkillsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 skillId) internal view returns (SkillsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 skillId, SkillType skillType, bytes memory skillStats) internal {
    bytes memory _staticData = encodeStatic(skillType);

    EncodedLengths _encodedLengths = encodeLengths(skillStats);
    bytes memory _dynamicData = encodeDynamic(skillStats);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 skillId, SkillType skillType, bytes memory skillStats) internal {
    bytes memory _staticData = encodeStatic(skillType);

    EncodedLengths _encodedLengths = encodeLengths(skillStats);
    bytes memory _dynamicData = encodeDynamic(skillStats);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 skillId, SkillsData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.skillType);

    EncodedLengths _encodedLengths = encodeLengths(_table.skillStats);
    bytes memory _dynamicData = encodeDynamic(_table.skillStats);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 skillId, SkillsData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.skillType);

    EncodedLengths _encodedLengths = encodeLengths(_table.skillStats);
    bytes memory _dynamicData = encodeDynamic(_table.skillStats);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (SkillType skillType) {
    skillType = SkillType(uint8(Bytes.getBytes1(_blob, 0)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (bytes memory skillStats) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    skillStats = (bytes(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (SkillsData memory _table) {
    (_table.skillType) = decodeStatic(_staticData);

    (_table.skillStats) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 skillId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 skillId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(SkillType skillType) internal pure returns (bytes memory) {
    return abi.encodePacked(skillType);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(bytes memory skillStats) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(skillStats).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(bytes memory skillStats) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((skillStats)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    SkillType skillType,
    bytes memory skillStats
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(skillType);

    EncodedLengths _encodedLengths = encodeLengths(skillStats);
    bytes memory _dynamicData = encodeDynamic(skillStats);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 skillId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = skillId;

    return _keyTuple;
  }
}
