// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { ResistanceStat } from "./../common.sol";

struct StatusEffectStatsData {
  int256 agiModifier;
  int256 armorModifier;
  int256 hpModifier;
  int256 intModifier;
  int256 damagePerTick;
  ResistanceStat resistanceStat;
  uint256 validTime;
  uint256 validTurns;
  uint256 cooldown;
}

library StatusEffectStats {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "StatusEffectStat", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462554400000000000000000000000053746174757345666665637453746174);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0101090020202020200120202000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes8)
  Schema constant _keySchema = Schema.wrap(0x0008010047000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (int256, int256, int256, int256, int256, uint8, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x010109003f3f3f3f3f001f1f1f00000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "effectId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](9);
    fieldNames[0] = "agiModifier";
    fieldNames[1] = "armorModifier";
    fieldNames[2] = "hpModifier";
    fieldNames[3] = "intModifier";
    fieldNames[4] = "damagePerTick";
    fieldNames[5] = "resistanceStat";
    fieldNames[6] = "validTime";
    fieldNames[7] = "validTurns";
    fieldNames[8] = "cooldown";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get agiModifier.
   */
  function getAgiModifier(bytes8 effectId) internal view returns (int256 agiModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get agiModifier.
   */
  function _getAgiModifier(bytes8 effectId) internal view returns (int256 agiModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set agiModifier.
   */
  function setAgiModifier(bytes8 effectId, int256 agiModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((agiModifier)), _fieldLayout);
  }

  /**
   * @notice Set agiModifier.
   */
  function _setAgiModifier(bytes8 effectId, int256 agiModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((agiModifier)), _fieldLayout);
  }

  /**
   * @notice Get armorModifier.
   */
  function getArmorModifier(bytes8 effectId) internal view returns (int256 armorModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get armorModifier.
   */
  function _getArmorModifier(bytes8 effectId) internal view returns (int256 armorModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set armorModifier.
   */
  function setArmorModifier(bytes8 effectId, int256 armorModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((armorModifier)), _fieldLayout);
  }

  /**
   * @notice Set armorModifier.
   */
  function _setArmorModifier(bytes8 effectId, int256 armorModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((armorModifier)), _fieldLayout);
  }

  /**
   * @notice Get hpModifier.
   */
  function getHpModifier(bytes8 effectId) internal view returns (int256 hpModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get hpModifier.
   */
  function _getHpModifier(bytes8 effectId) internal view returns (int256 hpModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set hpModifier.
   */
  function setHpModifier(bytes8 effectId, int256 hpModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((hpModifier)), _fieldLayout);
  }

  /**
   * @notice Set hpModifier.
   */
  function _setHpModifier(bytes8 effectId, int256 hpModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((hpModifier)), _fieldLayout);
  }

  /**
   * @notice Get intModifier.
   */
  function getIntModifier(bytes8 effectId) internal view returns (int256 intModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get intModifier.
   */
  function _getIntModifier(bytes8 effectId) internal view returns (int256 intModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set intModifier.
   */
  function setIntModifier(bytes8 effectId, int256 intModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((intModifier)), _fieldLayout);
  }

  /**
   * @notice Set intModifier.
   */
  function _setIntModifier(bytes8 effectId, int256 intModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((intModifier)), _fieldLayout);
  }

  /**
   * @notice Get damagePerTick.
   */
  function getDamagePerTick(bytes8 effectId) internal view returns (int256 damagePerTick) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get damagePerTick.
   */
  function _getDamagePerTick(bytes8 effectId) internal view returns (int256 damagePerTick) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set damagePerTick.
   */
  function setDamagePerTick(bytes8 effectId, int256 damagePerTick) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((damagePerTick)), _fieldLayout);
  }

  /**
   * @notice Set damagePerTick.
   */
  function _setDamagePerTick(bytes8 effectId, int256 damagePerTick) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((damagePerTick)), _fieldLayout);
  }

  /**
   * @notice Get resistanceStat.
   */
  function getResistanceStat(bytes8 effectId) internal view returns (ResistanceStat resistanceStat) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return ResistanceStat(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get resistanceStat.
   */
  function _getResistanceStat(bytes8 effectId) internal view returns (ResistanceStat resistanceStat) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return ResistanceStat(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set resistanceStat.
   */
  function setResistanceStat(bytes8 effectId, ResistanceStat resistanceStat) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked(uint8(resistanceStat)), _fieldLayout);
  }

  /**
   * @notice Set resistanceStat.
   */
  function _setResistanceStat(bytes8 effectId, ResistanceStat resistanceStat) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked(uint8(resistanceStat)), _fieldLayout);
  }

  /**
   * @notice Get validTime.
   */
  function getValidTime(bytes8 effectId) internal view returns (uint256 validTime) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get validTime.
   */
  function _getValidTime(bytes8 effectId) internal view returns (uint256 validTime) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set validTime.
   */
  function setValidTime(bytes8 effectId, uint256 validTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((validTime)), _fieldLayout);
  }

  /**
   * @notice Set validTime.
   */
  function _setValidTime(bytes8 effectId, uint256 validTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((validTime)), _fieldLayout);
  }

  /**
   * @notice Get validTurns.
   */
  function getValidTurns(bytes8 effectId) internal view returns (uint256 validTurns) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get validTurns.
   */
  function _getValidTurns(bytes8 effectId) internal view returns (uint256 validTurns) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set validTurns.
   */
  function setValidTurns(bytes8 effectId, uint256 validTurns) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((validTurns)), _fieldLayout);
  }

  /**
   * @notice Set validTurns.
   */
  function _setValidTurns(bytes8 effectId, uint256 validTurns) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((validTurns)), _fieldLayout);
  }

  /**
   * @notice Get cooldown.
   */
  function getCooldown(bytes8 effectId) internal view returns (uint256 cooldown) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get cooldown.
   */
  function _getCooldown(bytes8 effectId) internal view returns (uint256 cooldown) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set cooldown.
   */
  function setCooldown(bytes8 effectId, uint256 cooldown) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((cooldown)), _fieldLayout);
  }

  /**
   * @notice Set cooldown.
   */
  function _setCooldown(bytes8 effectId, uint256 cooldown) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((cooldown)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes8 effectId) internal view returns (StatusEffectStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes8 effectId) internal view returns (StatusEffectStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes8 effectId,
    int256 agiModifier,
    int256 armorModifier,
    int256 hpModifier,
    int256 intModifier,
    int256 damagePerTick,
    ResistanceStat resistanceStat,
    uint256 validTime,
    uint256 validTurns,
    uint256 cooldown
  ) internal {
    bytes memory _staticData = encodeStatic(
      agiModifier,
      armorModifier,
      hpModifier,
      intModifier,
      damagePerTick,
      resistanceStat,
      validTime,
      validTurns,
      cooldown
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes8 effectId,
    int256 agiModifier,
    int256 armorModifier,
    int256 hpModifier,
    int256 intModifier,
    int256 damagePerTick,
    ResistanceStat resistanceStat,
    uint256 validTime,
    uint256 validTurns,
    uint256 cooldown
  ) internal {
    bytes memory _staticData = encodeStatic(
      agiModifier,
      armorModifier,
      hpModifier,
      intModifier,
      damagePerTick,
      resistanceStat,
      validTime,
      validTurns,
      cooldown
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes8 effectId, StatusEffectStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.agiModifier,
      _table.armorModifier,
      _table.hpModifier,
      _table.intModifier,
      _table.damagePerTick,
      _table.resistanceStat,
      _table.validTime,
      _table.validTurns,
      _table.cooldown
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes8 effectId, StatusEffectStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.agiModifier,
      _table.armorModifier,
      _table.hpModifier,
      _table.intModifier,
      _table.damagePerTick,
      _table.resistanceStat,
      _table.validTime,
      _table.validTurns,
      _table.cooldown
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      int256 agiModifier,
      int256 armorModifier,
      int256 hpModifier,
      int256 intModifier,
      int256 damagePerTick,
      ResistanceStat resistanceStat,
      uint256 validTime,
      uint256 validTurns,
      uint256 cooldown
    )
  {
    agiModifier = (int256(uint256(Bytes.getBytes32(_blob, 0))));

    armorModifier = (int256(uint256(Bytes.getBytes32(_blob, 32))));

    hpModifier = (int256(uint256(Bytes.getBytes32(_blob, 64))));

    intModifier = (int256(uint256(Bytes.getBytes32(_blob, 96))));

    damagePerTick = (int256(uint256(Bytes.getBytes32(_blob, 128))));

    resistanceStat = ResistanceStat(uint8(Bytes.getBytes1(_blob, 160)));

    validTime = (uint256(Bytes.getBytes32(_blob, 161)));

    validTurns = (uint256(Bytes.getBytes32(_blob, 193)));

    cooldown = (uint256(Bytes.getBytes32(_blob, 225)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (StatusEffectStatsData memory _table) {
    (
      _table.agiModifier,
      _table.armorModifier,
      _table.hpModifier,
      _table.intModifier,
      _table.damagePerTick,
      _table.resistanceStat,
      _table.validTime,
      _table.validTurns,
      _table.cooldown
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes8 effectId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes8 effectId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    int256 agiModifier,
    int256 armorModifier,
    int256 hpModifier,
    int256 intModifier,
    int256 damagePerTick,
    ResistanceStat resistanceStat,
    uint256 validTime,
    uint256 validTurns,
    uint256 cooldown
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        agiModifier,
        armorModifier,
        hpModifier,
        intModifier,
        damagePerTick,
        resistanceStat,
        validTime,
        validTurns,
        cooldown
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    int256 agiModifier,
    int256 armorModifier,
    int256 hpModifier,
    int256 intModifier,
    int256 damagePerTick,
    ResistanceStat resistanceStat,
    uint256 validTime,
    uint256 validTurns,
    uint256 cooldown
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      agiModifier,
      armorModifier,
      hpModifier,
      intModifier,
      damagePerTick,
      resistanceStat,
      validTime,
      validTurns,
      cooldown
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes8 effectId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(effectId);

    return _keyTuple;
  }
}
