// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct UltimateDominionConfigData {
  bool locked;
  address goldToken;
  address characterToken;
  address items;
  address marketplace;
  address lootManager;
  address shop;
  uint256 maxPlayers;
}

library UltimateDominionConfig {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "UltimateDominion", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74625544000000000000000000000000556c74696d617465446f6d696e696f6e);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0099080001141414141414200000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bool, address, address, address, address, address, address, uint256)
  Schema constant _valueSchema = Schema.wrap(0x00990800606161616161611f0000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](8);
    fieldNames[0] = "locked";
    fieldNames[1] = "goldToken";
    fieldNames[2] = "characterToken";
    fieldNames[3] = "items";
    fieldNames[4] = "marketplace";
    fieldNames[5] = "lootManager";
    fieldNames[6] = "shop";
    fieldNames[7] = "maxPlayers";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get locked.
   */
  function getLocked() internal view returns (bool locked) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get locked.
   */
  function _getLocked() internal view returns (bool locked) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set locked.
   */
  function setLocked(bool locked) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((locked)), _fieldLayout);
  }

  /**
   * @notice Set locked.
   */
  function _setLocked(bool locked) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((locked)), _fieldLayout);
  }

  /**
   * @notice Get goldToken.
   */
  function getGoldToken() internal view returns (address goldToken) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get goldToken.
   */
  function _getGoldToken() internal view returns (address goldToken) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set goldToken.
   */
  function setGoldToken(address goldToken) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((goldToken)), _fieldLayout);
  }

  /**
   * @notice Set goldToken.
   */
  function _setGoldToken(address goldToken) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((goldToken)), _fieldLayout);
  }

  /**
   * @notice Get characterToken.
   */
  function getCharacterToken() internal view returns (address characterToken) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get characterToken.
   */
  function _getCharacterToken() internal view returns (address characterToken) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set characterToken.
   */
  function setCharacterToken(address characterToken) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((characterToken)), _fieldLayout);
  }

  /**
   * @notice Set characterToken.
   */
  function _setCharacterToken(address characterToken) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((characterToken)), _fieldLayout);
  }

  /**
   * @notice Get items.
   */
  function getItems() internal view returns (address items) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get items.
   */
  function _getItems() internal view returns (address items) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set items.
   */
  function setItems(address items) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((items)), _fieldLayout);
  }

  /**
   * @notice Set items.
   */
  function _setItems(address items) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((items)), _fieldLayout);
  }

  /**
   * @notice Get marketplace.
   */
  function getMarketplace() internal view returns (address marketplace) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get marketplace.
   */
  function _getMarketplace() internal view returns (address marketplace) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set marketplace.
   */
  function setMarketplace(address marketplace) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((marketplace)), _fieldLayout);
  }

  /**
   * @notice Set marketplace.
   */
  function _setMarketplace(address marketplace) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((marketplace)), _fieldLayout);
  }

  /**
   * @notice Get lootManager.
   */
  function getLootManager() internal view returns (address lootManager) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get lootManager.
   */
  function _getLootManager() internal view returns (address lootManager) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set lootManager.
   */
  function setLootManager(address lootManager) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((lootManager)), _fieldLayout);
  }

  /**
   * @notice Set lootManager.
   */
  function _setLootManager(address lootManager) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((lootManager)), _fieldLayout);
  }

  /**
   * @notice Get shop.
   */
  function getShop() internal view returns (address shop) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get shop.
   */
  function _getShop() internal view returns (address shop) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set shop.
   */
  function setShop(address shop) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((shop)), _fieldLayout);
  }

  /**
   * @notice Set shop.
   */
  function _setShop(address shop) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((shop)), _fieldLayout);
  }

  /**
   * @notice Get maxPlayers.
   */
  function getMaxPlayers() internal view returns (uint256 maxPlayers) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get maxPlayers.
   */
  function _getMaxPlayers() internal view returns (uint256 maxPlayers) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set maxPlayers.
   */
  function setMaxPlayers(uint256 maxPlayers) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((maxPlayers)), _fieldLayout);
  }

  /**
   * @notice Set maxPlayers.
   */
  function _setMaxPlayers(uint256 maxPlayers) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((maxPlayers)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (UltimateDominionConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (UltimateDominionConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bool locked,
    address goldToken,
    address characterToken,
    address items,
    address marketplace,
    address lootManager,
    address shop,
    uint256 maxPlayers
  ) internal {
    bytes memory _staticData = encodeStatic(
      locked,
      goldToken,
      characterToken,
      items,
      marketplace,
      lootManager,
      shop,
      maxPlayers
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bool locked,
    address goldToken,
    address characterToken,
    address items,
    address marketplace,
    address lootManager,
    address shop,
    uint256 maxPlayers
  ) internal {
    bytes memory _staticData = encodeStatic(
      locked,
      goldToken,
      characterToken,
      items,
      marketplace,
      lootManager,
      shop,
      maxPlayers
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(UltimateDominionConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.locked,
      _table.goldToken,
      _table.characterToken,
      _table.items,
      _table.marketplace,
      _table.lootManager,
      _table.shop,
      _table.maxPlayers
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(UltimateDominionConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.locked,
      _table.goldToken,
      _table.characterToken,
      _table.items,
      _table.marketplace,
      _table.lootManager,
      _table.shop,
      _table.maxPlayers
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      bool locked,
      address goldToken,
      address characterToken,
      address items,
      address marketplace,
      address lootManager,
      address shop,
      uint256 maxPlayers
    )
  {
    locked = (_toBool(uint8(Bytes.getBytes1(_blob, 0))));

    goldToken = (address(Bytes.getBytes20(_blob, 1)));

    characterToken = (address(Bytes.getBytes20(_blob, 21)));

    items = (address(Bytes.getBytes20(_blob, 41)));

    marketplace = (address(Bytes.getBytes20(_blob, 61)));

    lootManager = (address(Bytes.getBytes20(_blob, 81)));

    shop = (address(Bytes.getBytes20(_blob, 101)));

    maxPlayers = (uint256(Bytes.getBytes32(_blob, 121)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (UltimateDominionConfigData memory _table) {
    (
      _table.locked,
      _table.goldToken,
      _table.characterToken,
      _table.items,
      _table.marketplace,
      _table.lootManager,
      _table.shop,
      _table.maxPlayers
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    bool locked,
    address goldToken,
    address characterToken,
    address items,
    address marketplace,
    address lootManager,
    address shop,
    uint256 maxPlayers
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(locked, goldToken, characterToken, items, marketplace, lootManager, shop, maxPlayers);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bool locked,
    address goldToken,
    address characterToken,
    address items,
    address marketplace,
    address lootManager,
    address shop,
    uint256 maxPlayers
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      locked,
      goldToken,
      characterToken,
      items,
      marketplace,
      lootManager,
      shop,
      maxPlayers
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
