// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct WeaponStatsData {
  int256 agiModifier;
  int256 hpModifier;
  uint256 maxDamage;
  uint256 minDamage;
  uint256 minLevel;
  int256 strModifier;
  bytes32[] statusEffects;
}

library WeaponStats {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "UD", name: "WeaponStats", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74625544000000000000000000000000576561706f6e53746174730000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00c0060120202020202000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256)
  Schema constant _keySchema = Schema.wrap(0x002001001f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (int256, int256, uint256, uint256, uint256, int256, bytes32[])
  Schema constant _valueSchema = Schema.wrap(0x00c006013f3f1f1f1f3fc1000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "itemId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](7);
    fieldNames[0] = "agiModifier";
    fieldNames[1] = "hpModifier";
    fieldNames[2] = "maxDamage";
    fieldNames[3] = "minDamage";
    fieldNames[4] = "minLevel";
    fieldNames[5] = "strModifier";
    fieldNames[6] = "statusEffects";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get agiModifier.
   */
  function getAgiModifier(uint256 itemId) internal view returns (int256 agiModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get agiModifier.
   */
  function _getAgiModifier(uint256 itemId) internal view returns (int256 agiModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set agiModifier.
   */
  function setAgiModifier(uint256 itemId, int256 agiModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((agiModifier)), _fieldLayout);
  }

  /**
   * @notice Set agiModifier.
   */
  function _setAgiModifier(uint256 itemId, int256 agiModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((agiModifier)), _fieldLayout);
  }

  /**
   * @notice Get hpModifier.
   */
  function getHpModifier(uint256 itemId) internal view returns (int256 hpModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get hpModifier.
   */
  function _getHpModifier(uint256 itemId) internal view returns (int256 hpModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set hpModifier.
   */
  function setHpModifier(uint256 itemId, int256 hpModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((hpModifier)), _fieldLayout);
  }

  /**
   * @notice Set hpModifier.
   */
  function _setHpModifier(uint256 itemId, int256 hpModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((hpModifier)), _fieldLayout);
  }

  /**
   * @notice Get maxDamage.
   */
  function getMaxDamage(uint256 itemId) internal view returns (uint256 maxDamage) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get maxDamage.
   */
  function _getMaxDamage(uint256 itemId) internal view returns (uint256 maxDamage) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set maxDamage.
   */
  function setMaxDamage(uint256 itemId, uint256 maxDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((maxDamage)), _fieldLayout);
  }

  /**
   * @notice Set maxDamage.
   */
  function _setMaxDamage(uint256 itemId, uint256 maxDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((maxDamage)), _fieldLayout);
  }

  /**
   * @notice Get minDamage.
   */
  function getMinDamage(uint256 itemId) internal view returns (uint256 minDamage) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get minDamage.
   */
  function _getMinDamage(uint256 itemId) internal view returns (uint256 minDamage) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set minDamage.
   */
  function setMinDamage(uint256 itemId, uint256 minDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((minDamage)), _fieldLayout);
  }

  /**
   * @notice Set minDamage.
   */
  function _setMinDamage(uint256 itemId, uint256 minDamage) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((minDamage)), _fieldLayout);
  }

  /**
   * @notice Get minLevel.
   */
  function getMinLevel(uint256 itemId) internal view returns (uint256 minLevel) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get minLevel.
   */
  function _getMinLevel(uint256 itemId) internal view returns (uint256 minLevel) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set minLevel.
   */
  function setMinLevel(uint256 itemId, uint256 minLevel) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((minLevel)), _fieldLayout);
  }

  /**
   * @notice Set minLevel.
   */
  function _setMinLevel(uint256 itemId, uint256 minLevel) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((minLevel)), _fieldLayout);
  }

  /**
   * @notice Get strModifier.
   */
  function getStrModifier(uint256 itemId) internal view returns (int256 strModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Get strModifier.
   */
  function _getStrModifier(uint256 itemId) internal view returns (int256 strModifier) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (int256(uint256(bytes32(_blob))));
  }

  /**
   * @notice Set strModifier.
   */
  function setStrModifier(uint256 itemId, int256 strModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((strModifier)), _fieldLayout);
  }

  /**
   * @notice Set strModifier.
   */
  function _setStrModifier(uint256 itemId, int256 strModifier) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((strModifier)), _fieldLayout);
  }

  /**
   * @notice Get statusEffects.
   */
  function getStatusEffects(uint256 itemId) internal view returns (bytes32[] memory statusEffects) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get statusEffects.
   */
  function _getStatusEffects(uint256 itemId) internal view returns (bytes32[] memory statusEffects) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Set statusEffects.
   */
  function setStatusEffects(uint256 itemId, bytes32[] memory statusEffects) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((statusEffects)));
  }

  /**
   * @notice Set statusEffects.
   */
  function _setStatusEffects(uint256 itemId, bytes32[] memory statusEffects) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((statusEffects)));
  }

  /**
   * @notice Get the length of statusEffects.
   */
  function lengthStatusEffects(uint256 itemId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of statusEffects.
   */
  function _lengthStatusEffects(uint256 itemId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of statusEffects.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemStatusEffects(uint256 itemId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of statusEffects.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemStatusEffects(uint256 itemId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Push an element to statusEffects.
   */
  function pushStatusEffects(uint256 itemId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to statusEffects.
   */
  function _pushStatusEffects(uint256 itemId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from statusEffects.
   */
  function popStatusEffects(uint256 itemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from statusEffects.
   */
  function _popStatusEffects(uint256 itemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Update an element of statusEffects at `_index`.
   */
  function updateStatusEffects(uint256 itemId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of statusEffects at `_index`.
   */
  function _updateStatusEffects(uint256 itemId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(uint256 itemId) internal view returns (WeaponStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint256 itemId) internal view returns (WeaponStatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 itemId,
    int256 agiModifier,
    int256 hpModifier,
    uint256 maxDamage,
    uint256 minDamage,
    uint256 minLevel,
    int256 strModifier,
    bytes32[] memory statusEffects
  ) internal {
    bytes memory _staticData = encodeStatic(agiModifier, hpModifier, maxDamage, minDamage, minLevel, strModifier);

    EncodedLengths _encodedLengths = encodeLengths(statusEffects);
    bytes memory _dynamicData = encodeDynamic(statusEffects);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 itemId,
    int256 agiModifier,
    int256 hpModifier,
    uint256 maxDamage,
    uint256 minDamage,
    uint256 minLevel,
    int256 strModifier,
    bytes32[] memory statusEffects
  ) internal {
    bytes memory _staticData = encodeStatic(agiModifier, hpModifier, maxDamage, minDamage, minLevel, strModifier);

    EncodedLengths _encodedLengths = encodeLengths(statusEffects);
    bytes memory _dynamicData = encodeDynamic(statusEffects);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 itemId, WeaponStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.agiModifier,
      _table.hpModifier,
      _table.maxDamage,
      _table.minDamage,
      _table.minLevel,
      _table.strModifier
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.statusEffects);
    bytes memory _dynamicData = encodeDynamic(_table.statusEffects);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 itemId, WeaponStatsData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.agiModifier,
      _table.hpModifier,
      _table.maxDamage,
      _table.minDamage,
      _table.minLevel,
      _table.strModifier
    );

    EncodedLengths _encodedLengths = encodeLengths(_table.statusEffects);
    bytes memory _dynamicData = encodeDynamic(_table.statusEffects);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      int256 agiModifier,
      int256 hpModifier,
      uint256 maxDamage,
      uint256 minDamage,
      uint256 minLevel,
      int256 strModifier
    )
  {
    agiModifier = (int256(uint256(Bytes.getBytes32(_blob, 0))));

    hpModifier = (int256(uint256(Bytes.getBytes32(_blob, 32))));

    maxDamage = (uint256(Bytes.getBytes32(_blob, 64)));

    minDamage = (uint256(Bytes.getBytes32(_blob, 96)));

    minLevel = (uint256(Bytes.getBytes32(_blob, 128)));

    strModifier = (int256(uint256(Bytes.getBytes32(_blob, 160))));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (bytes32[] memory statusEffects) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    statusEffects = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_bytes32());
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (WeaponStatsData memory _table) {
    (
      _table.agiModifier,
      _table.hpModifier,
      _table.maxDamage,
      _table.minDamage,
      _table.minLevel,
      _table.strModifier
    ) = decodeStatic(_staticData);

    (_table.statusEffects) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 itemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 itemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    int256 agiModifier,
    int256 hpModifier,
    uint256 maxDamage,
    uint256 minDamage,
    uint256 minLevel,
    int256 strModifier
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(agiModifier, hpModifier, maxDamage, minDamage, minLevel, strModifier);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(bytes32[] memory statusEffects) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(statusEffects.length * 32);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(bytes32[] memory statusEffects) internal pure returns (bytes memory) {
    return abi.encodePacked(EncodeArray.encode((statusEffects)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    int256 agiModifier,
    int256 hpModifier,
    uint256 maxDamage,
    uint256 minDamage,
    uint256 minLevel,
    int256 strModifier,
    bytes32[] memory statusEffects
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(agiModifier, hpModifier, maxDamage, minDamage, minLevel, strModifier);

    EncodedLengths _encodedLengths = encodeLengths(statusEffects);
    bytes memory _dynamicData = encodeDynamic(statusEffects);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 itemId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    return _keyTuple;
  }
}
