services:
  - type: web
    name: ultimate-dominion-api
    env: node
    buildCommand: cd packages/api && pnpm install --no-frozen-lockfile && pnpm build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PINATA_JWT
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: WORLD_ADDRESS
        sync: false
      - key: INITIAL_BLOCK_NUMBER
        sync: false
      - key: PORT
        value: 8080
    autoDeploy: true
