// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum Classes {
  Warrior,
  Rogue,
  Mage
}

enum RngRequestType {
  CharacterStats,
  Combat,
  WorldGeneration
}

enum ItemType {
  Weapon,
  Armor,
  Spell,
  Potion,
  Material,
  QuestItem
}

enum MobType {
  Monster,
  NPC
}

enum Alignment {
  Loyalist,
  Neutral,
  Rebel,
  Aggro
}

enum EncounterType {
  PvP,
  PvE
}

enum SkillType {
  Temporary,
  PhysicalAttack,
  MagicAttack,
  StatusEffect
}

enum StatusEffects {
  ToHitModifier,
  DoT,
  HitPointMod,
  ArmorMod,
  WeaponMod,
  Stun
}
