// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum Classes {
  Warrior,
  Rogue,
  Mage
}

enum RngRequestType {
  CharacterStats,
  Combat,
  WorldGeneration
}

enum ItemType {
  Weapon,
  Armor,
  Spell,
<<<<<<< Updated upstream
  Potion,
<<<<<<< Updated upstream
  Utility,
=======
  Material,
=======
  Consumable,
>>>>>>> Stashed changes
>>>>>>> Stashed changes
  QuestItem
}

enum MobType {
  Monster,
  NPC
}

enum Alignment {
  Loyalist,
  Neutral,
  Rebel,
  Aggro
}

enum EncounterType {
  PvP,
  PvE
}

enum ActionType {
  Temporary,
  PhysicalAttack,
  MagicAttack,
  StatusEffect
}

<<<<<<< Updated upstream
=======
<<<<<<< Updated upstream
=======
enum ResistanceStat {
  Agility,
  Strength,
  Intelligence
}

>>>>>>> Stashed changes
enum OrderStatus {
  Canceled,
  Active,
  Fullfilled
}

enum TokenType {
  NATIVE,
  ERC20,
  ERC721,
  ERC1155
}

<<<<<<< Updated upstream
=======
>>>>>>> Stashed changes
>>>>>>> Stashed changes
enum StatusEffects {
  ToHitModifier,
  DoT,
  HitPointMod,
  ArmorMod,
  WeaponMod,
  Stun
}
