// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum Classes {
  Warrior,
  Rogue,
  Mage
}

enum RngRequestType {
  World,
  CharacterStats,
  Combat
}

enum ItemType {
  Weapon,
  Armor,
  Spell,
  Consumable,
  QuestItem
}

enum MobType {
  Monster,
  NPC
}

enum Alignment {
  Loyalist,
  Neutral,
  Rebel,
  Aggro
}

enum EncounterType {
  PvP,
  PvE,
  World
}

enum EffectType {
  Temporary,
  PhysicalDamage,
  MagicDamage,
  StatusEffect
}

enum ResistanceStat {
  None,
  Strength,
  Agility,
  Intelligence
}

enum OrderStatus {
  Canceled,
  Active,
  Fullfilled
}

enum TokenType {
  NATIVE,
  ERC20,
  ERC721,
  ERC1155
}

enum StatusEffects {
  ToHitModifier,
  DoT,
  HitPointMod,
  ArmorMod,
  WeaponMod,
  Stun
}
