// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Admin } from "./tables/Admin.sol";
import { Characters, CharactersData } from "./tables/Characters.sol";
import { Stats, StatsData } from "./tables/Stats.sol";
import { MapConfig } from "./tables/MapConfig.sol";
import { Spawned } from "./tables/Spawned.sol";
import { Mobs, MobsData } from "./tables/Mobs.sol";
import { MobsByLevel } from "./tables/MobsByLevel.sol";
import { Levels } from "./tables/Levels.sol";
import { CharacterEquipment, CharacterEquipmentData } from "./tables/CharacterEquipment.sol";
import { PvPFlag } from "./tables/PvPFlag.sol";
import { Counters } from "./tables/Counters.sol";
import { Items, ItemsData } from "./tables/Items.sol";
import { Actions, ActionsData } from "./tables/Actions.sol";
import { StarterItems, StarterItemsData } from "./tables/StarterItems.sol";
import { Name } from "./tables/Name.sol";
import { NameExists } from "./tables/NameExists.sol";
import { CombatEncounter, CombatEncounterData } from "./tables/CombatEncounter.sol";
import { PvPData, PvPDataData } from "./tables/PvPData.sol";
import { EncounterEntity, EncounterEntityData } from "./tables/EncounterEntity.sol";
import { RandomNumbers, RandomNumbersData } from "./tables/RandomNumbers.sol";
import { Position } from "./tables/Position.sol";
import { EntitiesAtPosition } from "./tables/EntitiesAtPosition.sol";
import { UltimateDominionConfig, UltimateDominionConfigData } from "./tables/UltimateDominionConfig.sol";
import { RngLogs, RngLogsData } from "./tables/RngLogs.sol";
import { ActionOutcome, ActionOutcomeData } from "./tables/ActionOutcome.sol";
import { CombatOutcome, CombatOutcomeData } from "./tables/CombatOutcome.sol";
