// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Admin } from "./tables/Admin.sol";
import { RandomNumbers, RandomNumbersData } from "./tables/RandomNumbers.sol";
import { Counters } from "./tables/Counters.sol";
import { Name } from "./tables/Name.sol";
import { NameExists } from "./tables/NameExists.sol";
import { Characters, CharactersData } from "./tables/Characters.sol";
import { Stats, StatsData } from "./tables/Stats.sol";
import { Mobs, MobsData } from "./tables/Mobs.sol";
import { MonsterStats, MonsterStatsData } from "./tables/MonsterStats.sol";
import { MobsByLevel } from "./tables/MobsByLevel.sol";
import { Levels } from "./tables/Levels.sol";
import { CharacterEquipment, CharacterEquipmentData } from "./tables/CharacterEquipment.sol";
import { Items, ItemsData } from "./tables/Items.sol";
import { StatRestrictions, StatRestrictionsData } from "./tables/StatRestrictions.sol";
import { WeaponStats, WeaponStatsData } from "./tables/WeaponStats.sol";
import { ArmorStats, ArmorStatsData } from "./tables/ArmorStats.sol";
import { SpellStats, SpellStatsData } from "./tables/SpellStats.sol";
import { ConsumableStats } from "./tables/ConsumableStats.sol";
import { StarterItems, StarterItemsData } from "./tables/StarterItems.sol";
import { Actions, ActionsData } from "./tables/Actions.sol";
import { PhysicalAttackStats, PhysicalAttackStatsData } from "./tables/PhysicalAttackStats.sol";
import { MagicAttackStats, MagicAttackStatsData } from "./tables/MagicAttackStats.sol";
import { StatusEffectStats, StatusEffectStatsData } from "./tables/StatusEffectStats.sol";
import { CombatEncounter, CombatEncounterData } from "./tables/CombatEncounter.sol";
import { EncounterEntity, EncounterEntityData } from "./tables/EncounterEntity.sol";
import { MapConfig } from "./tables/MapConfig.sol";
import { Spawned } from "./tables/Spawned.sol";
import { Position } from "./tables/Position.sol";
import { EntitiesAtPosition } from "./tables/EntitiesAtPosition.sol";
import { UltimateDominionConfig, UltimateDominionConfigData } from "./tables/UltimateDominionConfig.sol";
import { Orders, OrdersData } from "./tables/Orders.sol";
import { Considerations, ConsiderationsData } from "./tables/Considerations.sol";
import { Offers, OffersData } from "./tables/Offers.sol";
import { RngLogs, RngLogsData } from "./tables/RngLogs.sol";
import { ActionOutcome, ActionOutcomeData } from "./tables/ActionOutcome.sol";
import { CombatOutcome, CombatOutcomeData } from "./tables/CombatOutcome.sol";
