// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ActionType } from "@codegen/common.sol";

/**
 * @title IActionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IActionSystem {
  function UD__createAction(ActionType actionType, bytes memory actionStats) external returns (bytes32 actionId);
}
