// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CombatEncounterData, EncounterEntityData, StatsData } from "@codegen/index.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { ItemType, MobType, EffectType } from "@codegen/common.sol";

/**
 * @title IAdminSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAdminSystem {
  function UD__adminClearEncounterState(bytes32 entityId) external;

  function UD__adminSetCombatEncounter(bytes32 encounterId, CombatEncounterData memory encounterData) external;

  function UD__adminSetEncounterEntity(bytes32 entityId, EncounterEntityData memory encounterEntityData) external;

  function UD__setAdmin(address newAdmin, bool adminState) external;

  function UD__setMaxPlayers(uint256 newMax) external;

  function UD__adminDropGold(bytes32 characterId, uint256 goldAmount) external;

  function UD__adminDropItem(bytes32 characterId, uint256 itemId, uint256 amount) external;

  function UD__adminSetStats(bytes32 entityId, StatsData memory desiredStats) external;

  function UD__adminRemoveEntity(bytes32 entityId) external;

  function UD__adminMoveEntity(bytes32 entityId, uint16 x, uint16 y) external;

  function UD__getSystemAddress(ResourceId systemId) external view returns (address);

  function UD__adminApplyStatusEffect(bytes32 entityId, bytes32 statusEffectId) external;

  function UD__adminCreateItem(
    ItemType itemType,
    uint256 supply,
    uint256 dropChance,
    uint256 price,
    uint256 rarity,
    bytes memory stats,
    string memory itemMetadataURI
  ) external returns (uint256);

  function UD__adminCreateItems(
    ItemType[] memory itemTypes,
    uint256[] memory supply,
    uint256[] memory dropChances,
    uint256[] memory prices,
    uint256[] memory rarities,
    bytes[] memory stats,
    string[] memory itemMetadataURIs
  ) external;

  function UD__adminResupplyLootManager(uint256 itemId, uint256 newSupply) external;

  function UD__adminCreateMob(
    MobType mobType,
    bytes memory stats,
    string memory mobMetadataUri
  ) external returns (uint256);

  function UD__adminCreateMobs(
    MobType[] memory mobTypes,
    bytes[] memory stats,
    string[] memory mobMetadataURIs
  ) external;

  function UD__adminCreateEffect(
    EffectType effectType,
    string memory name,
    bytes memory effectStats
  ) external returns (bytes32);

  function UD__setGlobalDropMultiplier(uint256 newMult) external;

  function UD__setGoldDropMultiplier(uint256 newMult) external;
}
