// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Classes } from "@codegen/common.sol";
import { StatsData } from "@codegen/index.sol";

/**
 * @title ICharacterSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICharacterSystem {
  function UD__getName(bytes32 characterId) external view returns (bytes32 _name);

  function UD__getClass(bytes32 characterId) external view returns (Classes _class);

  function UD__getPlayerEntityId(uint256 characterTokenId) external view returns (bytes32 characterId);

  function UD__getCharacterTokenId(bytes32 characterId) external pure returns (uint256);

  function UD__getOwnerAddress(bytes32 characterId) external pure returns (address);

  function UD__isValidCharacterId(bytes32 characterId) external view returns (bool);

  function UD__isValidOwner(bytes32 characterId, address owner) external view returns (bool);

  function UD__mintCharacter(
    address account,
    bytes32 name,
    string memory tokenUri
  ) external returns (bytes32 characterId);

  function UD__rollStats(bytes32 userRandomNumber, bytes32 characterId, Classes class) external payable;

  function UD__enterGame(bytes32 characterId) external;

  function UD__getCurrentAvailableLevel(uint256 experience) external view returns (uint256 currentLevel);

  function UD__updateTokenUri(bytes32 characterId, string memory tokenUri) external;

  function UD__getOwner(bytes32 characterId) external view returns (address);

  function UD__getExperience(bytes32 characterId) external view returns (uint256);

  function UD__getStats(bytes32 characterId) external view returns (StatsData memory);
}
