// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EncounterType } from "@codegen/common.sol";
import { Action } from "@interfaces/Structs.sol";
import { CombatEncounterData } from "@codegen/index.sol";

/**
 * @title ICombatSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICombatSystem {
  function UD__createMatch(
    EncounterType encounterType,
    bytes32[] memory attackers,
    bytes32[] memory defenders
  ) external returns (bytes32 encounterId);

  function UD__isValidPvE(
    bytes32[] memory attackers,
    bytes32[] memory defenders,
    uint16 x,
    uint16 y
  ) external view returns (bool _isValidPvE);

  function UD__endTurn(bytes32 encounterId, bytes32 playerId, Action[] memory actions) external payable;

  function UD__isParticipant(bytes32 playerId, bytes32 encounterId) external view returns (bool _isParticipant);

  function UD__isParticipant(
    address account,
    bytes32[] memory participants
  ) external view returns (bool _isParticipant);

  function UD__executeCombat(uint256 prevRandao, bytes32 encounterId, Action[] memory actions) external;

  function UD__getEncounter(bytes32 encounterId) external view returns (CombatEncounterData memory _encounterData);

  function UD___calculateMagicAttack() external;
}
