// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EncounterType } from "@codegen/common.sol";
import { Action, PhysicalAttackStats } from "@interfaces/Structs.sol";

/**
 * @title ICombatSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICombatSystem {
  function UD__createMatch(
    EncounterType encounterType,
    bytes32[] memory attackers,
    bytes32[] memory defenders
  ) external returns (bytes32);

  function UD__endTurn(bytes32 encounterId, bytes32 playerId, Action[] memory actions) external;

  function UD__executeCombat(uint256 randomNumber, bytes32 encounterId, Action[] memory actions) external;

  function UD___calculatePhysicalAttack(
    PhysicalAttackStats memory attackStats,
    bytes32 attackerId,
    bytes32 defenderId,
    uint256 weaponId,
    uint256 randomNumber
  ) external returns (uint256 damage);

  function UD___calculateMagicAttack() external;
}
