// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EncounterType } from "@codegen/common.sol";
import { Action } from "@interfaces/Structs.sol";

/**
 * @title IEncounterSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEncounterSystem {
  function UD__createEncounter(
    EncounterType encounterType,
    bytes32[] calldata group1,
    bytes32[] calldata group2
  ) external returns (bytes32 encounterId);

  function UD__endTurn(bytes32 encounterId, bytes32 playerId, Action[] calldata attacks) external payable;
}
