// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { StatsData } from "@codegen/index.sol";
import { WeaponStats, ArmorStats } from "@interfaces/Structs.sol";

/**
 * @title IEquipmentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEquipmentSystem {
  function UD__equipItems(bytes32 characterId, uint256[] memory itemIds) external;

  function UD__isEquipped(bytes32 characterId, uint256 itemId) external view returns (bool _isEquipped);

  function UD__checkRequirements(bytes32 characterId, uint256 itemId) external view returns (bool);

  function UD__unequipItem(bytes32 characterId, uint256 itemId) external returns (bool success);

  function UD__applyEquipmentBonuses(bytes32 entityId) external view returns (StatsData memory modifiedStats);

  function UD__getWeaponStats(uint256 itemId) external view returns (WeaponStats memory _weaponStats);

  function UD__getArmorStats(uint256 itemId) external view returns (ArmorStats memory _ArmorStats);
}
