// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemType, Classes } from "@codegen/common.sol";
import { StatsData } from "@codegen/index.sol";
import { WeaponStats, ArmorStats } from "@interfaces/Structs.sol";

/**
 * @title IItemsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemsSystem {
  function UD__createItem(
    ItemType itemType,
    uint256 supply,
    bytes memory stats,
    string memory itemMetadataURI
  ) external returns (uint256);

  function UD__createItems(
    ItemType[] memory itemTypes,
    uint256[] memory supply,
    bytes[] memory stats,
    string[] memory itemMetadataURIs
  ) external;

  function UD__equipItems(bytes32 characterId, uint256[] memory itemIds) external;

  function UD__isEquipped(bytes32 characterId, uint256 itemId) external view returns (bool _isEquipped);

  function UD__checkRequirements(bytes32 characterId, uint256 itemId) external view returns (bool);

  function UD__unequipItem(bytes32 characterId, uint256 itemId) external returns (bool success);

  function UD__applyEquipmentBonuses(bytes32 entityId) external view returns (StatsData memory modifiedStats);

  function UD__getTotalSupply(uint256 tokenId) external view returns (uint256 _supply);

  function UD__issueStarterItems(bytes32 characterId) external;

  function UD__setTokenUri(uint256 tokenId, string memory tokenUri) external;

  function UD__getItemType(uint256 itemId) external view returns (ItemType);

  function UD__getWeaponStats(uint256 itemId) external view returns (WeaponStats memory _weaponStats);

  function UD__getArmorStats(uint256 itemId) external view returns (ArmorStats memory _ArmorStats);

  function UD__setStarterItems(Classes class, uint256[] memory itemIds, uint256[] memory amounts) external;
}
