// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILootManagerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILootManagerSystem {
  function UD__issueStarterItems(bytes32 characterId) external;

  function UD__dropGold(bytes32 characterId, uint256 amount) external;

  function UD__dropItem(bytes32 characterId, uint256 itemId, uint256 amount) external;

  function UD__dropItems(bytes32[] memory characterIds, uint256[] memory itemIds, uint256[] memory amounts) external;

  function UD__distributeRewards(
    bytes32 encounterId,
    uint256 randomNumber
  ) external returns (uint256 _expAmount, uint256 _goldAmount, uint256[] memory _itemIdsDropped);
}
