// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Action } from "@interfaces/Structs.sol";

/**
 * @title IPvESystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPvESystem {
  function UD__isValidPvE(
    bytes32[] memory attackers,
    bytes32[] memory defenders,
    uint16 x,
    uint16 y
  ) external view returns (bool _isValidPvE, bool _attackersAreMobs);

  function UD__executePvECombat(uint256 randomness, bytes32 encounterId, Action[] memory actions) external;
}
