// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Action } from "@interfaces/Structs.sol";

/**
 * @title IPvPSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPvPSystem {
  function UD__isValidPvP(
    bytes32[] memory attackers,
    bytes32[] memory defenders,
    uint16 x,
    uint16 y
  ) external view returns (bool _isValidPvP);

  function UD__executePvPCombat(uint256 prevRandao, bytes32 encounterId, Action[] memory actions) external;
}
