// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IUltimateDominionConfigSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IUltimateDominionConfigSystem {
  function UD__getCharacterToken() external view returns (address _characterToken);

  function UD__getGoldToken() external view returns (address _goldToken);

  function UD__getEntropy() external view returns (address _entropy);

  function UD__getPythProvider() external view returns (address _provider);
}
