/**
 * Static item description map extracted from zone JSON files.
 * Key: metadataUri (e.g. "armor:tattered_cloth")
 * Value: human-readable description
 */
export const ITEM_DESCRIPTIONS: Record<string, string> = {
  "armor:10x_engineers_hoodie": "Legend says wearing it makes you write code 10 times faster. The stains suggest otherwise.",
  "armor:acolyte_vestments": "White once. The prayer stitched into the collar is to a god that doesn't answer.",
  "armor:apprentice_robes": "Faded blue with a singed hem. The last wearer learned something the hard way.",
  "armor:caffeine_stained_hoodie": "The stains form a pattern. Some say it's a dependency graph.",
  "armor:cardboard_box_armor": "Amazon Prime packaging repurposed for battle. Two-day delivery, zero-day protection.",
  "armor:cargo_shorts_of_holding": "Eleven pockets. Each one deeper than the last. You lost your keys in one three sprints ago.",
  "armor:chainmail_shirt": "Heavy and well-kept. Whoever wore it before knew what they were doing.",
  "armor:cracked_stone_plate": "Carved from the giant's own armor. It cracked when he fell. Still heavier than anything you've lifted.",
  "armor:duct_tape_patch": "Slapped on in a hurry. Holds about as well as a hotfix on Friday.",
  "armor:leather_jerkin": "Cut from something tougher than cow. The stitching holds.",
  "armor:load_bearing_comment_vest": "Remove this and everything falls apart. Don't ask why.",
  "armor:mage_robes": "The fabric hums faintly. You can feel it when the cave goes quiet.",
  "armor:mechanical_keyboard_shield": "Cherry MX Blues. The clacking alone is a defensive mechanism.",
  "armor:noise_canceling_cloak": "Blocks all incoming sound. And most incoming damage.",
  "armor:padded_armor": "Layered cloth packed with cave straw. Crude but honest protection.",
  "armor:ranger_leathers": "Supple and dark. Made for someone who expected to be hunted.",
  "armor:rusty_chainmail": "Half the links are missing. Still stops a bite.",
  "armor:scorched_scale_vest": "Peeled from something that breathed fire. The scales are still warm.",
  "armor:scout_armor": "Light enough to run in. That matters down here.",
  "armor:senior_devs_bathrobe": "Worn by someone who hasn't left the house in three sprints. Radiates authority.",
  "armor:server_rack_plate": "Ripped from a decommissioned rack. Still warm.",
  "armor:spider_silk_wraps": "Impossibly light. The silk doesn't tear \u2014 you have to cut it.",
  "armor:stalkers_cloak": "The edges seem to blur in dim light. You feel less visible wearing it.",
  "armor:standing_desk_fortress": "Motorized and reinforced. Raises to block incoming attacks.",
  "armor:studded_leather": "Iron studs hammered into boiled hide. Cave-made, but sturdy.",
  "armor:tattered_cloth": "Stitched together from whatever was at hand. Better than nothing.",
  "armor:the_firewall": "Literal flames. Nothing gets through. Except UDP.",
  "armor:the_incognito_tab": "You feel invisible wearing it. Your ISP disagrees.",
  "armor:trash_bag_poncho": "Waterproof. Tear-proof is another story.",
  "armor:worn_leather_vest": "Cracked and stiff. Somebody died wearing this.",
  "consumable:bloodrage_tonic": "Thick and red. Your muscles swell but the world feels fragile.",
  "consumable:stoneskin_salve": "Hardens your skin to stone. Moving gets harder. Getting hit gets easier.",
  "consumable:trollblood_ale": "Brewed from something best not named. Strength surges. Thought retreats.",
  "consumable:venom_vial": "Sealed with wax. The glass is already corroding from the inside.",
  "consumable:spore_cloud": "Crushed cave fungus in a thin pouch. One squeeze and the mind goes foggy.",
  "consumable:sapping_poison": "Soak a blade or throw the bottle. Either way, they swing softer.",
  "consumable:antidote_sh": "chmod +x antidote.sh && ./antidote.sh. Cures all status effects.",
  "consumable:bent_nail": "Pulled from a coffin. Or a wall. Hard to say.",
  "consumable:cave_moss": "Damp and faintly luminescent. Alchemists might pay for it.",
  "consumable:cracked_bone": "Could be human. Could be something else.",
  "consumable:deprecated_api_key": "Stopped working three versions ago. Someone will still buy it.",
  "consumable:dull_crystal": "Barely catches the light. Worth a few coins to the right buyer.",
  "consumable:emergency_coffee": "Black. No sugar. No time for that. Heals 15 HP and your will to live.",
  "consumable:energy_drink_of_haste": "Glows an unnatural green. Your heart rate doubles. Heals 30 HP.",
  "consumable:expired_ssl_certificate": "Your connection is not private. Neither is this item.",
  "consumable:focusing_rubber_duck": "Explain your problems to it. Somehow, you understand everything better. +5 INT.",
  "consumable:focusing_tea": "Brewed from cave herbs. The world narrows to a point.",
  "consumable:fortifying_stew": "Thick, grey, and vaguely warm. Your arms feel steadier after.",
  "consumable:fortifying_stress_ball": "Squeeze hard enough and you feel stronger. +5 STR.",
  "consumable:greater_health_potion": "Thick and amber. Closes wounds you can watch.",
  "consumable:health_potion": "Cleaner than the minor version. Somebody knew what they were brewing.",
  "consumable:minor_health_potion": "Tastes like copper and moss. It works.",
  "consumable:orphaned_todo_comment": "// TODO: fix this later. That was three years ago.",
  "consumable:outdated_readme": "Claims the project runs on Node 12. It doesn't.",
  "consumable:pizza_slice_of_vigor": "Cold. Day-old. Still the best thing you've eaten this sprint. Heals 50 HP.",
  "consumable:quickening_berries": "Bitter and bright red. Your hands shake for a moment, then everything feels faster.",
  "consumable:quickening_energy_drink": "Warning: may cause jitters, twitching, and inhuman reflexes. +5 AGI.",
  "consumable:rat_tooth": "Small, sharp, and useless for anything but selling.",
  "consumable:single_node_module": "One of 847,000. Heavier than it looks.",
  "consumable:sudo_rm_rf": "Deletes everything in sight. Use with extreme caution. Blinds the enemy.",
  "consumable:tattered_hide": "Stripped from something that didn't survive the cave.",
  "consumable:unused_import_statement": "It's just sitting there. Taking up space. Like most of your dependencies.",
  "weapon:apprentice_staff": "Ash wood with a copper cap. Hums when you grip it too tight.",
  "weapon:bone_staff": "Cold to the touch. The marrow inside is black and still.",
  "weapon:broken_sword": "Snapped at the hilt. The edge still cuts if you hold it right.",
  "weapon:brutes_cleaver": "Chipped from use, not neglect. The brute knew how to hit.",
  "weapon:channeling_rod": "Iron wrapped in copper wire. The tip glows faintly in the dark.",
  "weapon:code_review_crossbow": "Fires pointed comments with surgical precision. Each bolt leaves a red mark.",
  "weapon:console_log_staff": "The first tool any developer reaches for. Prints your enemies to the console.",
  "weapon:cracked_wand": "Split down the middle. The magic leaks out like heat from a cracked lantern.",
  "weapon:crystal_blade": "Grown, not forged. The edge is sharper than steel but brittle.",
  "weapon:darkwood_bow": "The wood is so dark it drinks the torchlight. Silent to draw.",
  "weapon:debuggers_breakpoint": "Stops everything in its tracks. Including your enemies.",
  "weapon:etched_blade": "Someone scratched symbols into the flat of the blade. They might mean something.",
  "weapon:giants_club": "A stone column broken from the cave wall. The giant called it a weapon.",
  "weapon:git_blame_dagger": "Points directly at the one responsible. Twist for extra damage.",
  "weapon:hotfix_hammer": "When in doubt, hit it harder. Bypasses all review processes.",
  "weapon:hunting_bow": "Built for game, not war. It'll do for both.",
  "weapon:iron_axe": "Functional. Heavy. Not made for elegance.",
  "weapon:keyboard_warrior_blade": "Forged from a thousand angry comments. The edge is pure vitriol.",
  "weapon:lgtm_stamp_of_doom": "Approved without review. The consequences are catastrophic.",
  "weapon:linuss_flamethrower": "For when the code is so bad it needs to be burned. Fires harsh reviews.",
  "weapon:longbow": "Yew wood, well-oiled. Reach matters when the cave opens up.",
  "weapon:mage_staff": "Oak core with iron banding. The wood grain follows no natural pattern.",
  "weapon:mouse_click_dagger": "Double-click for double damage. Triple-click selects the whole enemy.",
  "weapon:pair_programming_staff": "Two heads are better than one. The staff whispers suggestions.",
  "weapon:rage_quit_greatsword": "Forged in frustration. Each swing carries the weight of a thousand failed builds.",
  "weapon:rat_kings_fang": "Pulled from a jaw the size of your head. The venom still weeps from the root.",
  "weapon:recurve_bow": "Compact and tense. Pulls harder than it looks.",
  "weapon:refactor_blade": "Cuts clean. Leaves the codebase better than it found it.",
  "weapon:rubber_duck_mace": "Squeaks on impact. Surprisingly effective.",
  "weapon:smoldering_rod": "The tip glows like a dying ember. It never goes out.",
  "weapon:sporecap_wand": "Carved from a fungal stalk. Pulses with a slow, living warmth.",
  "weapon:stack_trace_scythe": "Carves through problems layer by layer. Shows you exactly where it hurts.",
  "weapon:steel_mace": "Dented but solid. Doesn't need an edge to break bones.",
  "weapon:the_mass_revert": "One swing undoes everything. git reset --hard made physical.",
  "weapon:trackpad_shuriken": "Pried from a MacBook. Flies true if you remember the gesture.",
  "weapon:trolls_bonebreaker": "A femur sharpened to a point. The troll used it on everything.",
  "weapon:warhammer": "Too heavy to swing fast. You only need to swing it once.",
  "weapon:webspinner_bow": "Strung with spider silk. The arrows fly silent.",
  "weapon:worn_shortbow": "The string frays at both ends. Every shot might be the last.",
  "weapon:zero_day_exploit": "Nobody saw it coming. Nobody can patch it in time.",
};
