/**
 * Static item description map extracted from zone JSON files.
 * Key: metadataUri (e.g. "armor:tattered_cloth")
 * Value: human-readable description
 */
export const ITEM_DESCRIPTIONS: Record<string, string> = {
  "armor:10x_engineers_hoodie": "Legend says wearing it makes you write code 10 times faster. The stains suggest otherwise.",
  "armor:acolyte_vestments": "White once. The prayer stitched into the collar is to a god that doesn't answer.",
  "armor:apprentice_robes": "Faded blue with a singed hem. The last wearer learned something the hard way.",
  "armor:drakes_cowl": "Stitched from drake membrane. The cowl whispers when you channel through it.",
  "armor:caffeine_stained_hoodie": "The stains form a pattern. Some say it's a dependency graph.",
  "armor:cardboard_box_armor": "Amazon Prime packaging repurposed for battle. Two-day delivery, zero-day protection.",
  "armor:cargo_shorts_of_holding": "Eleven pockets. Each one deeper than the last. You lost your keys in one three sprints ago.",
  "armor:etched_chainmail": "Heavy and well-kept. Whoever wore it before knew what they were doing.",
  "armor:carved_stone_plate": "Carved from the giant's own armor. Etched with runes that glow faintly in darkness.",
  "armor:duct_tape_patch": "Slapped on in a hurry. Holds about as well as a hotfix on Friday.",
  "armor:leather_jerkin": "Cut from something tougher than cow. The stitching holds.",
  "armor:load_bearing_comment_vest": "Remove this and everything falls apart. Don't ask why.",
  "armor:mage_robes": "The fabric hums faintly. You can feel it when the cave goes quiet.",
  "armor:mechanical_keyboard_shield": "Cherry MX Blues. The clacking alone is a defensive mechanism.",
  "armor:noise_canceling_cloak": "Blocks all incoming sound. And most incoming damage.",
  "armor:padded_armor": "Layered cloth packed with cave straw. Crude but honest protection.",
  "armor:ranger_leathers": "Supple and dark. Made for someone who expected to be hunted.",
  "armor:rusty_chainmail": "Half the links are missing. Still stops a bite.",
  "armor:scorched_scale_vest": "Peeled from something that breathed fire. The scales are still warm.",
  "armor:scout_armor": "Light enough to run in. That matters down here.",
  "armor:senior_devs_bathrobe": "Worn by someone who hasn't left the house in three sprints. Radiates authority.",
  "armor:server_rack_plate": "Ripped from a decommissioned rack. Still warm.",
  "armor:spider_silk_wraps": "Impossibly light. The silk doesn't tear \u2014 you have to cut it.",
  "armor:stalkers_cloak": "The edges seem to blur in dim light. You feel less visible wearing it.",
  "armor:standing_desk_fortress": "Motorized and reinforced. Raises to block incoming attacks.",
  "armor:studded_leather": "Iron studs hammered into boiled hide. Cave-made, but sturdy.",
  "armor:tattered_cloth": "Stitched together from whatever was at hand. Better than nothing.",
  "armor:the_firewall": "Literal flames. Nothing gets through. Except UDP.",
  "armor:the_incognito_tab": "You feel invisible wearing it. Your ISP disagrees.",
  "armor:trash_bag_poncho": "Waterproof. Tear-proof is another story.",
  "armor:worn_leather_vest": "Cracked and stiff. Somebody died wearing this.",
  "consumable:bloodrage_tonic": "Thick and red. Your muscles swell but the world feels fragile.",
  "consumable:stoneskin_salve": "Hardens your skin to stone. Moving gets harder. Getting hit gets easier.",
  "consumable:trollblood_ale": "Brewed from something best not named. Strength surges. Thought retreats.",
  "consumable:venom_vial": "Sealed with wax. The glass is already corroding from the inside.",
  "consumable:spore_cloud": "Crushed cave fungus in a thin pouch. One squeeze and the mind goes foggy.",
  "consumable:sapping_poison": "Soak a blade or throw the bottle. Either way, they swing softer.",
  "consumable:antidote_sh": "chmod +x antidote.sh && ./antidote.sh. Cures all status effects.",
  "consumable:bent_nail": "Pulled from a coffin. Or a wall. Hard to say.",
  "consumable:cave_moss": "Damp and faintly luminescent. Alchemists might pay for it.",
  "consumable:cracked_bone": "Could be human. Could be something else.",
  "consumable:deprecated_api_key": "Stopped working three versions ago. Someone will still buy it.",
  "consumable:dull_crystal": "Barely catches the light. Worth a few coins to the right buyer.",
  "consumable:emergency_coffee": "Black. No sugar. No time for that. Heals 15 HP and your will to live.",
  "consumable:energy_drink_of_haste": "Glows an unnatural green. Your heart rate doubles. Heals 30 HP.",
  "consumable:expired_ssl_certificate": "Your connection is not private. Neither is this item.",
  "consumable:focusing_rubber_duck": "Explain your problems to it. Somehow, you understand everything better. +5 INT.",
  "consumable:focusing_tea": "Brewed from cave herbs. The world narrows to a point.",
  "consumable:fortifying_stew": "Thick, grey, and vaguely warm. Your arms feel steadier after.",
  "consumable:fortifying_stress_ball": "Squeeze hard enough and you feel stronger. +5 STR.",
  "consumable:greater_health_potion": "Thick and amber. Closes wounds you can watch.",
  "consumable:health_potion": "Cleaner than the minor version. Somebody knew what they were brewing.",
  "consumable:minor_health_potion": "Tastes like copper and moss. It works.",
  "consumable:orphaned_todo_comment": "// TODO: fix this later. That was three years ago.",
  "consumable:outdated_readme": "Claims the project runs on Node 12. It doesn't.",
  "consumable:pizza_slice_of_vigor": "Cold. Day-old. Still the best thing you've eaten this sprint. Heals 50 HP.",
  "consumable:quickening_berries": "Bitter and bright red. Your hands shake for a moment, then everything feels faster.",
  "consumable:quickening_energy_drink": "Warning: may cause jitters, twitching, and inhuman reflexes. +5 AGI.",
  "consumable:rat_tooth": "Small, sharp, and useless for anything but selling.",
  "consumable:single_node_module": "One of 847,000. Heavier than it looks.",
  "consumable:sudo_rm_rf": "Deletes everything in sight. Use with extreme caution. Blinds the enemy.",
  "consumable:tattered_hide": "Stripped from something that didn't survive the cave.",
  "consumable:unused_import_statement": "It's just sitting there. Taking up space. Like most of your dependencies.",
  "weapon:apprentice_staff": "Ash wood with a copper cap. Hums when you grip it too tight.",
  "weapon:bone_staff": "Cold to the touch. The marrow inside is black and still.",
  "weapon:broken_sword": "Snapped at the hilt. The edge still cuts if you hold it right.",
  "weapon:brutes_cleaver": "Heavy and chipped. Whoever used this didn't bother with finesse.",
  "weapon:channeling_rod": "Iron wrapped in copper wire. The tip glows faintly in the dark.",
  "weapon:code_review_crossbow": "Fires pointed comments with surgical precision. Each bolt leaves a red mark.",
  "weapon:console_log_staff": "The first tool any developer reaches for. Prints your enemies to the console.",
  "weapon:cracked_wand": "Split down the middle. The magic leaks out like heat from a cracked lantern.",
  "weapon:crystal_blade": "A fragment of something larger. The facets catch light that isn't there.",
  "weapon:darkwood_bow": "The wood is so dark it drinks the torchlight. Silent to draw.",
  "weapon:debuggers_breakpoint": "Stops everything in its tracks. Including your enemies.",
  "weapon:etched_blade": "The notches along the edge aren't decoration. They're a tally.",
  "weapon:giants_club": "Carved from a single boulder. Slow but absolute.",
  "weapon:git_blame_dagger": "Points directly at the one responsible. Twist for extra damage.",
  "weapon:hotfix_hammer": "When in doubt, hit it harder. Bypasses all review processes.",
  "weapon:hunting_bow": "Built for game, not war. It'll do for both.",
  "weapon:iron_axe": "Functional. Heavy. Not made for elegance.",
  "weapon:keyboard_warrior_blade": "Forged from a thousand angry comments. The edge is pure vitriol.",
  "weapon:lgtm_stamp_of_doom": "Approved without review. The consequences are catastrophic.",
  "weapon:linuss_flamethrower": "For when the code is so bad it needs to be burned. Fires harsh reviews.",
  "weapon:longbow": "Yew wood, well-oiled. Reach matters when the cave opens up.",
  "weapon:mage_staff": "Oak core with iron banding. The wood grain follows no natural pattern.",
  "weapon:mouse_click_dagger": "Double-click for double damage. Triple-click selects the whole enemy.",
  "weapon:pair_programming_staff": "Two heads are better than one. The staff whispers suggestions.",
  "weapon:rage_quit_greatsword": "Forged in frustration. Each swing carries the weight of a thousand failed builds.",
  "weapon:rat_kings_fang": "Longer than your forearm. The venom glands still weep.",
  "weapon:recurve_bow": "Simple and reliable. Gets the job done without complaint.",
  "weapon:refactor_blade": "Cuts clean. Leaves the codebase better than it found it.",
  "weapon:rubber_duck_mace": "Squeaks on impact. Surprisingly effective.",
  "weapon:smoldering_rod": "The tip glows like a dying ember. It never goes out.",
  "weapon:sporecap_wand": "Carved from a fungal stalk. Pulses with a slow, living warmth.",
  "weapon:stack_trace_scythe": "Carves through problems layer by layer. Shows you exactly where it hurts.",
  "weapon:light_mace": "Light enough to swing one-handed. The dents are from something that doesn't dent easily.",
  "weapon:shortbow": "Simple and reliable. Gets the job done without complaint.",
  "weapon:notched_blade": "The notches along the edge aren't decoration. They're a tally.",
  "weapon:notched_cleaver": "Heavy and chipped. Whoever used this didn't bother with finesse.",
  "weapon:crystal_shard": "A fragment of something larger. The facets catch light that isn't there.",
  "weapon:gnarled_cudgel": "Twisted wood hardened by cave damp. Hits like a grudge.",
  "weapon:stone_maul": "Carved from a single boulder. Slow but absolute.",
  "weapon:dire_rat_fang": "Longer than your forearm. The venom glands still weep.",
  "weapon:trollhide_cleaver": "The blade is wrapped in troll hide that refuses to rot. Cuts deeper the harder you swing.",
  "weapon:phasefang": "Shimmers at the edges like a heat mirage. Strikes from angles that shouldn't exist.",
  "weapon:drakescale_staff": "Scaled in drake hide with a core of compressed flame. The air warps around it.",
  "weapon:basilisk_fangs": "Each fang drips with venom that smells of copper and decay.",
  "weapon:petrifying_gaze": "Not a weapon you hold. A weapon that holds you.",
  "weapon:the_mass_revert": "One swing undoes everything. git reset --hard made physical.",
  "weapon:trackpad_shuriken": "Pried from a MacBook. Flies true if you remember the gesture.",
  "weapon:trolls_bonebreaker": "Twisted wood hardened by cave damp. Hits like a grudge.",
  "weapon:warhammer": "Too heavy to swing fast. You only need to swing it once.",
  "weapon:webspinner_bow": "Strung with spider silk. The arrows fly silent.",
  "weapon:worn_shortbow": "The string frays at both ends. Every shot might be the last.",
  "weapon:zero_day_exploit": "Nobody saw it coming. Nobody can patch it in time.",

  // ==================== Zone 2: Windy Peaks ====================

  // --- Monsters ---
  "monster:ridge_stalker": "Lean and low to the ground. It watches from the ridgelines, patient as stone, until it isn't.",
  "monster:frost_wraith": "The cold didn't kill it. The cold is what it became.",
  "monster:granite_sentinel": "Carved by hands or grown by the mountain \u2014 no one's sure. It guards the path and doesn't negotiate.",
  "monster:gale_phantom": "More wind than creature. You hear it before you see it, and by then it's behind you.",
  "monster:blighthorn": "Where it grazes, nothing grows. The decay rides in its breath.",
  "monster:storm_shrike": "Lightning dances between its feathers. It screams and the thunder answers.",
  "monster:hollow_scout": "Wears the remnants of a faction uniform. Doesn't serve either side anymore.",
  "monster:ironpeak_charger": "Built like the mountain itself. When it charges, the ground remembers.",
  "monster:peakfire_wraith": "Born where the stone still holds Korrath's heat. It burns cold.",
  "monster:korraths_warden": "A soldier who climbed the peak and found something that wouldn't let go. The armor isn't his. He doesn't care.",

  // --- STR Weapons ---
  "weapon:ridgestone_hammer": "Chipped from the mountain's own rock. Every swing carries the weight of the peak.",
  "weapon:peak_cleaver": "Forged at a mountain camp. The edge holds despite the wind.",
  "weapon:windforged_axe": "The blade hums in strong wind. Whoever made it understood the peaks.",
  "weapon:wardens_maul": "Pulled from a dead man's hands at the summit. The grip is still warm.",

  // --- AGI Weapons ---
  "weapon:scrub_bow": "Bent from scrub wood that grows sideways in the wind. Shoots true enough.",
  "weapon:gale_bow": "The draw is light. Arrows fly like the wind itself carried them.",
  "weapon:stormfeather_bow": "Fletched with feathers from something that flew through storms. Doesn't miss in wind.",
  "weapon:peakwind_longbow": "The string sings a note you can feel in your chest. Range that makes the peaks feel small.",

  // --- INT Weapons ---
  "weapon:frozen_shard": "A splinter of ice that won't melt. It cuts the air when you point it.",
  "weapon:rime_staff": "White wood crusted with permanent frost. The cold comes from inside it.",
  "weapon:stormglass_rod": "Glass that survived a lightning strike. The crack inside pulses.",
  "weapon:wraith_beacon": "It doesn't cast light. It casts attention. Things come when you raise it.",

  // --- Hybrid Weapons ---
  "weapon:wardens_ember": "A blade that glows like a coal. The Warden's heat lingers in the steel.",
  "weapon:windweaver": "Light as air, sharp as spite. The magic and the edge are the same thing.",
  "weapon:ridgefang": "Tooth of something that lived inside the mountain. Cuts and keeps cutting.",
  "weapon:viperstrike": "Fast and venomous. Named by someone who didn't survive to rename it.",
  "weapon:ashveil_staff": "Charred wood from a lightning-struck tree. The magic tastes like smoke.",

  // --- Plate Armor ---
  "armor:peakstone_mail": "Mountain stone links threaded with iron. Heavy and honest.",
  "armor:ridgeforged_plate": "Hammered at a ridge forge by someone who stayed too long. Good work.",
  "armor:windsworn_plate": "Scored by decades of mountain wind. The dents are a map of storms survived.",
  "armor:wardens_bulwark": "Taken from the summit. The metal is warm and hums when storms approach.",

  // --- Leather Armor ---
  "armor:mountain_hide": "Thick-skinned beast leather, poorly cured. Smells like altitude.",
  "armor:galebound_leather": "Supple and windproof. Made by someone who knew the peaks.",
  "armor:stormhide_vest": "The hide crackles with static. Whatever wore this skin lived in the storms.",
  "armor:phantom_shroud": "You can see through it in certain light. Or maybe you can't see what's behind it.",

  // --- Cloth Armor ---
  "armor:frostweave_robe": "Woven from threads that hold the cold. You feel sharper wearing it.",
  "armor:mistcloak": "Grey as the mountain mist. Hard to see. Hard to hit.",
  "armor:wraith_vestments": "The fabric moves when the air doesn't. Something in the weave still remembers.",
  "armor:ember_mantle": "Warm without fire. The lining glows faintly where Korrath's heat seeped into the thread.",

  // --- Spells (L15) ---
  "spell:warcry": "A battle roar that sharpens steel and hardens resolve. One cry to turn the tide.",
  "spell:judgment": "Holy wrath made manifest. The guilty find their strength failing.",
  "spell:volley": "A rain of arrows. No single shot — a storm.",
  "spell:backstab": "One strike, placed perfectly. The target never sees it coming.",
  "spell:regrowth": "The forest mends what battle breaks. Roots knit bone, bark seals wounds.",
  "spell:blight": "Everything rots. Strength, speed, wit — all of it fades under the curse.",
  "spell:meteor": "A shard of raw arcane force, called from above. Nothing subtle about it.",
  "spell:mana_burn": "Drains the weave from your enemy. Their magic gutters like a candle in wind.",
  "spell:smite": "Holy fire that heals the righteous and scorches the wicked. Both at once.",
};
