[profile.default]
solc = "0.8.24"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1
via_ir = true
verbosity = 2
cbor_metadata = false
bytecode_hash = "none"
memory_limit = 1073741824
src = "src"
test = "test"
out = "out"
target_evm = "cancun"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
]
extra_output_files = ["abi", "evm.bytecode"]
fs_permissions = [{ access = "read-write", path = "./" }]
libs = ["node_modules"]

[profile.base-mainnet]
# eth_rpc_url sourced from ETH_RPC_URL env var (set in .env.testnet / .env.mainnet)
